### ISSUE TITLE
Flaky failure in two javascript tests

### ISSUE THREAD

**Issue by gnprice** [tree-sitter/tree-sitter#112] opened 2017-10-31 05:18 UTC
I ran across this by chance on a `script/test` run. Glad the test script prints out its random seed!

```
$ script/test -s 1509425801
make: Nothing to be done for 'tests'.
Random seed: 1509425801
Executed 32654 tests. 32653 succeeded. 2 failed.
There were failures!

the javascript language parses one invalid subtree right after the viable prefix: repairing an insertion of "eydcelnt(]{" at 31:
Found changed scope outside of any invalidated range;
Position: {2, 26}
Byte index: 52
Line:   x = function(a) { b; } function(c) { d; }
                                ^
Old scopes: (vector: program, if_statement, statement_block, expression_statement, ERROR, function, function, 'u')
New scopes: (vector: program, if_statement, statement_block, expression_statement, assignment_expression, function, function, 'u')
Invalidated ranges:
  {{2, 5}, {2, 25}}


the javascript language parses one invalid subtree right after the viable prefix: repairing an insertion of "eydcelnt(]{" at 31:
test/integration/real_grammars.cc:47: Expected: of length 0
Actual: [ 339 ]


Test run complete. 32654 tests run. 32653 succeeded. 2 failed.

real	0m21.685s
user	0m21.152s
sys	0m0.300s
```

**Comment by maxbrunsfeld** [comment] 2018-03-08 17:33
I think the cause of these failures was fixed in 1e04489e5088fecb3e032f4681aa397282bdea02. I'm not 100% sure, but I'm going to close this out because these tests no longer exist in their current form; I had to change them because of some big change to the error recovery algorithm.

**Closed by maxbrunsfeld** 2018-03-08 17:33 UTC
