### ISSUE TITLE
Highlighting test gets stuck if first line of test file is a comment

### ISSUE THREAD

**Issue by mr-martian** [tree-sitter/tree-sitter#1827] opened 2022-07-30 03:12 UTC
If the very first line of a syntax highlighting test is a comment, then even if `tree-sitter highlight` colors the file correctly and essentially instantly, `tree-sitter test` loops seemingly endlessly until killed. On the half-dozen grammars I tried this with, simply adding a blank line before the comment was sufficient to fix this behavior.

If relevant:
```
$ tree-sitter --version
tree-sitter 0.19.3 (24785cdb39ad2740ca33c111490984333787f5d3)
```

**Comment by amaanq** [comment] 2024-08-31 05:18
Tested this in 3 grammars, can't reproduce now so I'll close this out

**Closed by amaanq** 2024-08-31 05:18 UTC
