### ISSUE TITLE
language attribute lost after update test.

### ISSUE THREAD

**Issue by cathaysia** [tree-sitter/tree-sitter#3511] opened 2024-08-02 13:26 UTC
### Problem

I wrote a corpus test like this:

```
======================
list after paragraph
:language(loongdoc)
======================

block1
+
block2

-----

```

after run `tree-sitter test -u`, then it become:

```
======================
list after paragraph
======================

block1
+
block2

-----

(document
  (section_block
    (paragraph
      (line)))
  (list_continuation)
  (section_block
    (paragraph
      (line))))
````

The language attribute lost.

### Steps to reproduce

no

### Expected behavior

cli should only update `output` node.

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.22.6 (b40f342067a89cd6331bf4c27407588320f3c263)

### Operating system/version

fedora 40

**Comment by ObserverOfTime** [comment] 2024-08-02 14:19
Duplicate of #3479

**Closed by ObserverOfTime** 2024-08-02 14:19 UTC
Labels: bug
