### ISSUE TITLE
Store generated files as GH release artifacts instead of checking them into git repositories

### ISSUE THREAD

**Issue by FelipeLema** [tree-sitter/tree-sitter#730] opened 2020-09-11 15:05 UTC
From what I've read in several places (eg [here](https://github.com/tree-sitter/tree-sitter/issues/240#issuecomment-442184073), [here](https://github.com/tree-sitter/tree-sitter-julia/pull/14#issuecomment-689143890)) tree-sitter-{lang} repos are meant to provide generated source code (like src/parse.c, src/grammar.json) for other people to consume for their own use.

However, I would like to refute the idea that these files must be provided within the source tree (version controlled with the rest of the source  code). I'm stating reasons why would one get generated files out of the source tree and tools / ways to still provide generated code.

why do it?
==

-   they hinder resolving diffs (even when resolved, it would need to be re-resolved in the future) across branches.
-   they hinder concurrent development (harder to solve diffs when more people work on code at the same time).
-   they hinder development by adding responsibility to developers (more things a dev must be aware of while working on something) when it can actually be deferred.

tools / ways to handle and distribute generated files
==

- testing could be done using a Makefile (or any kind of dependency resolver) to do tree-sitter generate before tree-sitter test (no need to keep track of them).
- generated source files (eg src/parser.c) can still be offered as a download (for consumers of "a Tree-sitter language") by adding a CI release package that includes generated source files (CI runs tree-sitter generate and packs them).

related: https://github.com/tree-sitter/tree-sitter-julia/issues/16, tree-sitter/tree-sitter#240

**Comment by patrickt** [comment] 2020-09-11 15:20
I don’t think that this would be a good change to make on the tree-sitter side of things. This workflow would add complexity to every single consumer of the tree-sitter repositories, especially our already-published packages that depend on embedded C files for their publishing workflow.

If you’re running into problems re. tooling and diffing the generated .c files, I’d recommend adding a `.gitattributes` file that turns off the `-diff` attribute, as seen [here](https://www.git-scm.com/docs/gitattributes#_marking_files_as_binary). Though they are indeed large, I think it’s a feature, not a bug, that they can be embedded in a source repository, as that provides a record of exactly what parser was being used at a given point, rather than making it implicit with respect both to the grammar and the `tree-sitter` CLI version. Besides, the diffs associated with your `grammar.js` are going to be far more informative, in the grand scheme of things, than any diff associated with the generated code.

**Comment by FelipeLema** [comment] 2020-09-11 20:14
Could you expand on the complexities you are thinking about? Grammar consumers downloading a tar file will keep on doing so (just a different URL). Using git submodules could be replaced with a tar download, which can still point to a specific commit in any branch, since CI allows forks to have their own release packages (assuming developers stay in the Github ecosystem). On the same matter, why would one use git submodules for consuming generated (binary) files? I can understand either using submodules for source code or downloads for generated binaries. Using submodules to handle binaries sounds like an overkill, as commit diffs and branching are worthless ("you should look at source code to understand") and harder to read.

Yes, a grammar developer could use `.gitattributes` when having diff problems. This still makes the developer responsible for resolving diffs of generated files (by marking them as binary) instead of diffs of source code (grammar.js), as stated in the "why" section above.

CIs provide the same info of what parser is being used at any given point, as they match a commit with a packaged tar. Delegating the responsibility of matching source code with generated code a grammar developer is something that is bound to break (actually happened to me).

I'm thinking at scale, where every grammar developer will have to sit down and spend time research ingdifferent ways of resolving diffs for generated code. Also, breaking generated code by not resolving it properly can _unknowingly_ break grammar consumers flow. This is something that is not unlikely to happen.

**Comment by maxbrunsfeld** [comment] 2020-11-30 20:16
I think we may move in this direction at some point. My rough idea of a plan would be:

1. Add `tree-sitter` CLI subcommands for packaging and uploading the generated files to the GitHub releases API. Possibly just a `tree-sitter publish [github-repo-url]` command that can automatically discover your github repository using your `package.json` and/or your `.git/config`. It would also be good to have a `tree-sitter pack` command that just creates the tarball, but does not upload it anywhere.
2. Update the CI of every existing Tree-sitter grammar in the `tree-sitter` org repo to start using `tree-sitter publish` on tagged commits.
3. Change the build process for all of GitHub's internal applications to consume the parsers via the GitHub releases API instead of using git submodules.
4. Publish a blog post somewhere informing all of the existing Tree-sitter users that they will no longer be able to consume `parser.c` and other generated files directly from the git repository.
5. Remove the generated files from all of the grammar repositories.

This is probably not something we'll start work on right away, because it will take some further conversations to validate this design, and a lot of communication with existing consumers. And we have a lot of other things that we're working on. But just wanted to write down this plan somewhere public.

**Comment by milahu** [comment] 2020-12-01 09:24
detail: would be nice to mark auto-generated files with a header comment, like
```c
// this file was auto-generated on 2020-07-20 from tree-sitter-html version 7f442e1

**Comment by milahu** [comment] 2020-12-03 12:02
small workaround to exclude files from `git diff`

```sh
git config alias.diff2 "diff -- :/ ':(exclude,top)src/grammar.json' \
  ':(exclude,top)src/node-types.json' ':(exclude,top)src/parser.c'"
git diff2
```

**Comment by ObserverOfTime** [comment] 2024-10-13 15:18
There is now a [reusable release workflow](https://github.com/tree-sitter/workflows#release-workflow) for this purpose, so it's time to close this issue.
Note, however, that it's not _yet_ used by any parsers, nor supported by downstream consumers.

**Closed by ObserverOfTime** 2024-10-13 15:18 UTC
Labels: enhancement

**Comment by toshinori985-cell** [comment] 2025-08-21 19:41
> I think we may move in this direction at some point. My rough idea of a plan would be:
> 
> 1. Add `tree-sitter` CLI subcommands for packaging and uploading the generated files to the GitHub releases API. Possibly just a `tree-sitter publish [github-repo-url]` command that can automatically discover your github repository using your `package.json` and/or your `.git/config`. It would also be good to have a `tree-sitter pack` command that just creates the tarball, but does not upload it anywhere.
> 2. Update the CI of every existing Tree-sitter grammar in the `tree-sitter` org repo to start using `tree-sitter publish` on tagged commits.
> 3. Change the build process for all of GitHub's internal applications to consume the parsers via the GitHub releases API instead of using git submodules.
> 4. Publish a blog post somewhere informing all of the existing Tree-sitter users that they will no longer be able to consume `parser.c` and other generated files directly from the git repository.
> 5. Remove the generated files from all of the grammar repositories.
> 
> This is probably not something we'll start work on right away, because it will take some further conversations to validate this design, and a lot of communication with existing consumers. And we have a lot of other things that we're working on. But just wanted to write down this plan somewhere public.
