### ISSUE TITLE
Running a query inside Docker causes a breaking error.

### ISSUE THREAD

**Issue by c4lliope** [tree-sitter/tree-sitter#894] opened 2021-01-25 02:45 UTC
Hi Max!

I'm building ~A COOL PROGRAM~ [over here](https://github.com/assembleapp/hierarch);
you can see on the `docker` branch I'm trying to wrap everything up in Docker and `docker-compose`
so I can use K8S to launch online demo pages for people on demand.

So -- my `node hierarch` command runs using `tree-sitter` and `tree-sitter-javascript`, no problem, on plain old `node`.

As soon as I begin using my `docker-compose` program, my code errors and dies on the first tree-sitter query it runs.

- using my `docker-compose.yml` and many reboots -
![Screen Shot 2021-01-24 at 9 42 19 PM](https://user-images.githubusercontent.com/30454698/105654939-10315400-5e8d-11eb-8231-be1f00b6e89f.png)

I'm stumped; no idea how to debug or begin working around this issue.
Perhaps I'll try the [`web-tree-sitter`](https://github.com/tree-sitter/tree-sitter/blob/d6a3e4c98c3cca213b02ba4de933e9860d204d96/lib/binding_web/README.md) binding in the morning,
and see if the error goes bye-bye.

Any help, much needed.

CC @donokuda because he's a cool dude.

**Comment by c4lliope** [comment] 2021-01-25 14:37
> Perhaps I'll try the web-tree-sitter binding in the morning,

I'm not thrilled to try this out, because I need all the speed I can get in this program, and the approach is described as "considerably slower". A node-binding approach is ideal, so I'm still stumped.

Happy Monday!

**Comment by c4lliope** [comment] 2021-01-25 15:18
> I'm not thrilled to try this out

...so instead, i made a small reproduction of my issue, like so:

```bash
eagle:~ grace$ mkdir place/hierarch/reproduce
eagle:~ grace$ cd place/hierarch/reproduce
eagle:reproduce grace$ cp ../hierarch/Dockerfile .
eagle:reproduce grace$ yarn add tree-sitter tree-sitter-javascript

eagle:reproduce grace$ cat > run.js
const Parser = require("tree-sitter")
const JavaScript = require("tree-sitter-javascript")

const program = 'const label = () => ("Chillhop Music")' 
const parser = new Parser()
parser.setLanguage(JavaScript)
const parsed = parser.parse(program)

const query = new Parser.Query(JavaScript, '(variable_declarator (identifier) @name)')                
const matches = query.matches(parsed.rootNode)
console.log(matches.length)
^D

eagle:reproduce grace$ git init
eagle:reproduce grace$ git add Dockerfile run.js
eagle:reproduce grace$ git add package.json yarn.lock
eagle:reproduce grace$ git commit -m 'reproduce error, i hope.'
[master (root-commit) 7278a6f] reproduce error, i hope.
 4 files changed, 473 insertions(+)
 create mode 100644 Dockerfile
 create mode 100644 package.json
 create mode 100644 run.js
 create mode 100644 yarn.lock

eagle:reproduce grace$ git remote add origin git@github.com:assembleapp/hierarch-reproduce.git
eagle:reproduce grace$ git branch -M main
eagle:reproduce grace$ git push -u origin main
```

-> https://github.com/assembleapp/hierarch-reproduce

**Comment by c4lliope** [comment] 2021-01-25 16:52
![Screen Shot 2021-01-25 at 11 35 24 AM](https://user-images.githubusercontent.com/30454698/105736467-d1d67c00-5f02-11eb-9fb4-d256fa393ea7.png)

My error seems to be cropping up [here](https://github.com/assembleapp/hierarch/blob/docker/hierarch/program.js#L76),
which oddly enough - is inside a `try/catch` block.
The program runs `console.log('making query')`, and ends before `console.log('running query')`;
so the problem is in parsing / making the query object.

Also odd: [one query][1] in my codebase is running, no problem. That's the `24` output in the image, ^.
It's only [the query labeled `A.1`][2] which causes the break.

Since the error occurs inside a `try {}`, seems like no exception is being raised;
the error causes the process to exit immediately with code 139.

Sadly, my small `hierarch-reproduce` codebase didn't replicate the error properly, so it's no use.

Can you see any difference between my [simple][1] and [complex][2] queries that would cause only the second one to error?

Much obliged!

[1]: https://github.com/assembleapp/hierarch/blob/docker/hierarch/parse.js#L398-L400
[2]: https://github.com/assembleapp/hierarch/blob/docker/hierarch/parse.js#L23-L41

**Comment by c4lliope** [comment] 2021-01-25 17:41
I copy/paste my query into my `hierarch-reproduce` codebase, and I see an error. Yay! Minimally reproduced.

Please see my [README](https://github.com/assembleapp/hierarch-reproduce).

The error code is more detailed there, also; seems like a `TSQueryErrorNodeType` occurs, only in docker.

**Comment by c4lliope** [comment] 2021-01-29 14:53
In [assembleapp/hierarch-reproduce](https://github.com/assembleapp/hierarch-reproduce),
I tried a couple variations on my query.
ALL of these queries compile on plain-old, non-docker node.
SOME raise TSQueryErrorNodeType errors inside Docker.

> ❌  error
```
    (jsx_element
	open_tag: (
	    jsx_opening_element
	    name: (_) @opening-name
	    attribute: (jsx_attribute (property_identifier) @_original "=" (jsx_expression (_) @original))
	    attribute: (jsx_attribute (property_identifier) @_code "=" (string) @code)
	)

	(#eq? @opening-name "Box")
	(#eq? @_original "original")
	(#eq? @_code "code")
    ) @element
```


> ✅  no errors
```
    (jsx_element
	open_tag: (
	    jsx_opening_element
	    attribute: (jsx_attribute (property_identifier) @_original "=" (jsx_expression (_) @original))
	    attribute: (jsx_attribute (property_identifier) @_code "=" (string) @code)
	)

	(#eq? @_original "original")
	(#eq? @_code "code")
    ) @element
```


✅  no errors
```
    (jsx_element
	open_tag: (
	    jsx_opening_element
	    name: (_) @opening-name
	    attribute: (jsx_attribute (property_identifier) @_original "=" (jsx_expression (_) @original))
	)

	(#eq? @opening-name "Box")
	(#eq? @_original "original")
    ) @element
```


✅  no errors
```
    (jsx_element
	open_tag: (
	    jsx_opening_element
	    name: (_) @opening-name
	    attribute: (jsx_attribute (property_identifier) @_code "=" (string) @code)
	)

	(#eq? @opening-name "Box")
	(#eq? @_code "code")
    ) @element
```

So roughly, dropping any single named child of the `open_tag` in my query is enough to make the query run properly.
Sadly, I need all those named children (`opening-name`, `_code`, and `_original`) in my query.

And again, all queries run no problem when Docker is not in the mix.
Any help, @maxbrunsfeld ? Much obliged!

**Comment by c4lliope** [comment] 2021-02-18 21:56
Closing; I'll be moving my app's logic into the browser now that I've worked around #925.
No more need to be running such a complex Docker process.

**Comment by cellog** [comment] 2021-02-21 04:47
I'm not sure it makes sense to close this - it's a real bug, even if your use case doesn't need it to be fixed.

**Comment by c4lliope** [comment] 2021-04-16 00:47
Reopening, I suppose.

**Comment by amaanq** [comment] 2024-12-17 07:07
It's a bit tough to actually debug this because there's no clear instructions on reproducing (and looks like you've updated your repo to no longer use the commands Docker?), though I would definitely want to know if this is still reproducible. For now, I'll close this out, but if you have any more info/can indeed confirm the bug with a minimal reproducer, I'd be happy to reopen :slightly_smiling_face:

**Closed by amaanq** 2024-12-17 07:07 UTC
