### ISSUE TITLE
munmap_chunk(): invalid pointer Aborted (core dumped) error when parsing big weird cpp file

### ISSUE THREAD

**Issue by Tomerg1** [tree-sitter/tree-sitter#2156] opened 2023-03-26 13:10 UTC
The file I trying to parse can be found here:
github.com/muntorg/munt-official/blob/master/src/data/static_diff_data.cpp

I suspect that the created tree is too big. 

my system is
python3 running on Ubuntu 20.4

**Comment by ahlinc** [comment] 2023-03-26 13:18
Could you test it with tree-sitter CLI?

**Comment by Tomerg1** [comment] 2023-03-27 08:33
I tested it with the CLI and got the error: "munmap_chunk(): invalid pointer"

**Comment by Tomerg1** [comment] 2023-03-27 08:47
I tested it with the CLI and got the error: "munmap_chunk(): invalid pointer"

**Comment by ahlinc** [comment] 2023-04-07 09:51
It doesn't reproducible for me on Fedora 37 with Tree-sitter build from the master branch:
```sh
# script run -c 'cargo r -- p ~/Downloads/static_diff_data.cpp'
Script started on 2023-04-07 12:47:06+03:00 [COMMAND="cargo r -- p ~/Downloads/static_diff_data.cpp" TERM="xterm-kitty" TTY="/dev/pts/0" COLUMNS="191" LINES="110"]
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/tree-sitter p /home/ahlinc/Downloads/static_diff_data.cpp`
(ERROR [0, 0] - [169535, 99]
  (number_literal [0, 0] - [0, 9])
  (number_literal [0, 10] - [0, 19])
.....
  (number_literal [169534, 90] - [169534, 99])
  (number_literal [169535, 0] - [169535, 9])
  (number_literal [169535, 10] - [169535, 19])
  (number_literal [169535, 20] - [169535, 29])
  (comma_expression [169535, 30] - [169535, 99]
    left: (number_literal [169535, 30] - [169535, 39])
    right: (comma_expression [169535, 40] - [169535, 99]
      left: (number_literal [169535, 40] - [169535, 49])
      right: (comma_expression [169535, 50] - [169535, 99]
        left: (number_literal [169535, 50] - [169535, 59])
        right: (comma_expression [169535, 60] - [169535, 99]
          left: (number_literal [169535, 60] - [169535, 69])
          right: (comma_expression [169535, 70] - [169535, 99]
            left: (number_literal [169535, 70] - [169535, 79])
            right: (comma_expression [169535, 80] - [169535, 99]
              left: (number_literal [169535, 80] - [169535, 89])
              right: (number_literal [169535, 90] - [169535, 99]))))))))
/home/ahlinc/Downloads/static_diff_data.cpp     4515 ms (ERROR [0, 0] - [169535, 99])

Script done on 2023-04-07 12:47:21+03:00 [COMMAND_EXIT_CODE="1"]
```
It parses with errors but it's fine as it doesn't crushes.

@Tomerg1 Could you try a Tree-sitter CLI build from the master branch?

**Comment by ahlinc** [comment] 2023-04-07 09:58
@Tomerg1 additional note, could you tell a versions or better a commit hashes for python binding that you use and `tree-sitter-cpp` grammar? I suspect that the issue may by in the `tree-sitter-cpp` grammar's [scanner.cc](https://github.com/tree-sitter/tree-sitter-cpp/blob/master/src/scanner.cc).

**Comment by amaanq** [comment] 2024-01-29 22:32
seems like a duplicate of https://github.com/tree-sitter/py-tree-sitter/issues/186, please ensure your tree-sitter version is up to date

**Closed by amaanq** 2024-01-29 22:32 UTC
