### ISSUE TITLE
Is it normal for an `end` node to have a `child_count` > 0 ?

### ISSUE THREAD

**Issue by stackmystack** [tree-sitter/tree-sitter#1832] opened 2022-08-03 05:57 UTC
Is it normal for an `end` node to have a `child_count` > 0 ?

I am writing a visitor for the tree, and when I visit the `end` node, I see it has children, so I try to access them, except that it segfaults on me.

I am trying it on the `javascript` parser, and I don't see any `end` node declared in their grammar, so I am assuming it's a special node of the library.

_Originally posted by @stackmystack in https://github.com/tree-sitter/tree-sitter/discussions/1814_

**Comment by amaanq** [comment] 2024-08-31 05:27
I'm not sure how you're surfacing the `end` node, since that's a private/internal node that is not visible by default, if you can provide a reproducer that'd be great, otherwise I'll close this out

**Closed by amaanq** 2024-08-31 05:27 UTC
Labels: question
