### ISSUE TITLE
query choice operator is non-commutative

### ISSUE THREAD

**Issue by yuriv** [tree-sitter/tree-sitter#3258] opened 2024-04-05 07:10 UTC
### Problem

Tree-sitter query choice operator is non-commutative. Run tree-sitter query with `decl_succ.scm` and `var0.c` it would produce proper captures then run `decl_fail.scm` it would produce nothing. The differences between query files are opposite argument 's order of the top-level choice operator only.

decl_succ.scm

[sources.tar.gz](https://github.com/tree-sitter/tree-sitter/files/14881150/sources.tar.gz)

### Steps to reproduce

git clone --depth=1 https://github.com/tree-sitter/tree-sitter-c
cd tree-sitter-c
tree-sitter generate
add tree-sitter-c parser to tree-sitter config
tree-sitter query decl_succ.scm var0.c
tree-sitter query decl_fail.scm var0.c

### Actual behavior
$ cat decl_succ.scm 
(declaration (primitive_type) @tt [(init_declarator) @id [(attributed_declarator) @ad (identifier) @ii]]) @dd
$ tree-sitter query decl_succ.scm var0.c 
var0.c
  pattern: 0
    capture: 4 - dd, start: (0, 0), end: (0, 6), text: `int k;`
    capture: 0 - tt, start: (0, 0), end: (0, 3), text: `int`
    capture: 3 - ii, start: (0, 4), end: (0, 5), text: `k`

$ cat decl_fail.scm 
(declaration (primitive_type) @tt [[(attributed_declarator) @ad (identifier) @ii] (init_declarator) @id]) @dd
$ tree-sitter query decl_fail.scm var0.c 
var0.c

### Expected behavior
$ tree-sitter query decl_succ.scm var0.c 
var0.c
  pattern: 0
    capture: 4 - dd, start: (0, 0), end: (0, 6), text: `int k;`
    capture: 0 - tt, start: (0, 0), end: (0, 3), text: `int`
    capture: 3 - ii, start: (0, 4), end: (0, 5), text: `k`

$ tree-sitter query decl_fail.scm var0.c 
var0.c
  pattern: 0
    capture: 4 - dd, start: (0, 0), end: (0, 6), text: `int k;`
    capture: 0 - tt, start: (0, 0), end: (0, 3), text: `int`
    capture: 3 - ii, start: (0, 4), end: (0, 5), text: `k`

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.22.2

### Operating system/version

Rocky Linux 8.9

**Comment by WillLillis** [comment] 2024-04-05 16:42
Looks related to/ is a duplicate of #1811

**Comment by ObserverOfTime** [comment] 2024-04-12 07:53
It does indeed seem to be a duplicate of #1811 rather than #3239.

**Closed by ObserverOfTime** 2024-04-12 07:53 UTC
Labels: bug
