### ISSUE TITLE
anonymousFunctionExprNodes.flatMap is not a function

### ISSUE THREAD

**Issue by Augustin82** [tree-sitter/tree-sitter#599] opened 2020-04-17 14:51 UTC
Hi there!

I'm using neovim + CoC.vim + elm-language-server, which uses tree-sitter. One of the features is "go to definition" (GTD), which takes one to the place where symbol under the cursor is defined. Recently, I have noticed that some symbols, when trying to resulted in an error from CoC: "definition not found". Looking at the error log, the error is:
```Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: anonymousFunctionExprNodes.flatMap is not a function
  Code: -32603```
This comes from `treeUtils.js` in the elm-language-server code, which does this:
```      const anonymousFunctionExprNodes = this.descendantsOfType(
        node,
        "anonymous_function_expr",
      );
      const match = anonymousFunctionExprNodes
        .flatMap((a) => a.children)
        .find(
          (child) =>
            child.type === "pattern" && child.text === functionParameterName,
        );
```
So it would seem that `descendantsOfType` returns null/undefined, instead of an Array.

You can read more of my investigation here in my initial bug report at elm-language-server: https://github.com/elm-tooling/elm-language-server/issues/254

This bug does not occur in VSCode, even though it seems the elm-language-server code is the same, so this may be due to an interaction with (neo)vim and CoC.

Is there anything I can do to clarifiy the issue?

Many thanks!

**Comment by Razzeee** [comment] 2020-04-17 15:28
I also looked at the code that seems to generate the result https://github.com/tree-sitter/tree-sitter/blob/1635aab801152b8b36975dbc6cd02ea01ddbf778/lib/binding_web/binding.js#L387-L399

I'm not sure how it is possible to end up in this state.

**Comment by maxbrunsfeld** [comment] 2020-04-17 16:54
I'm going to close this one out for now because currently, it sounds like you are investigating an issue with `elm-language-server` or `tree-sitter-elm`.

If you end up narrowing down the bug to a specific issue with the Tree-sitter library, then you could create a minimal reproduction script that demonstrates the problem (outside of the elm-language-server) and and open an issue here. Thanks!

**Closed by maxbrunsfeld** 2020-04-17 16:54 UTC

**Comment by Augustin82** [comment] 2020-04-17 16:59
Apologies for posting in the wrong place, thanks for pointing me in the right direction!
