### ISSUE TITLE
Create call graph with tree-sitter

### ISSUE THREAD

**Issue by shaicantor** [tree-sitter/tree-sitter#1603] opened 2022-01-19 12:06 UTC
Hi there,

Is there an option to create a call graph with tree-sitter for search based navigation?
Like the article suggests - https://docs.github.com/en/repositories/working-with-files/using-files/navigating-code-on-github#about-navigating-code-on-github

If so, can you please provide some guidelines or guide on how to do that?
Thanks

**Comment by dcreager** [comment] 2022-01-19 13:41
Duplicate of discussion thread at #1605

**Closed by dcreager** 2022-01-19 13:41 UTC
