### ISSUE TITLE
Getting line number in scanner.c.

### ISSUE THREAD

**Issue by m-kru** [tree-sitter/tree-sitter#1282] opened 2021-07-20 07:08 UTC
Is it possible to get the current line number in `scanner.c`? I would like to use it to provide more robust error messages to the user in case of syntax errors. `TSLexer` has 

> uint32_t (*get_column)(TSLexer *) - (Experimental) A function for querying the current column position of the lexer. It returns the number of unicode code points (not bytes) since the start of the current line.

However, it looks like there is no method or attribute to get the current line number.

**Comment by ahlinc** [comment] 2021-07-20 08:23
No, it's not possible.
The external scanner is a very low level thing that intended for specific purposes.
How do you see that the `scanner.c` can be involved into error messages provisioning?

**Comment by m-kru** [comment] 2021-07-20 11:22
@ahlinc For example like this: `errx(EXIT_FAILURE, "Expected foo, found bar")`.
The context may be important here. I am defining grammar not for a text editor integration but for language prototyping.

**Comment by ahlinc** [comment] 2021-07-20 11:39
@m-kru Hmm, got it, I've used something similiar in a grammar development process to debug my external scanner.
I see it's enough for you to stop the parser right in a place of some error in the external scanner, but the same doesn't possible for any terminals defined in the `grammar.js` file. Tree-sitter was designed to recover from errors and parse to the end of input in any way. Do you plan to define all your terminals as external tokens?

**Comment by m-kru** [comment] 2021-07-21 08:14
@ahlinc Not all terminals are external tokens, but all external tokes are terminal. Is it even possible to parse non-terminal as external token?

**Comment by ahelwer** [comment] 2021-07-21 12:54
@m-kru kind of, but not really - you would have to parse it as something like `(external_marker_start) (nonterminal) (external_marker_end)` where `nonterminal` is defined in the grammar.

**Comment by ahlinc** [comment] 2021-07-21 19:09
> Is it even possible to parse non-terminal as external token?

No, external scanners are soleily a complement for tree-sitter's lexer and the production of non-terminals is the parser resbonsibility.

**Comment by MeepTech** [comment] 2023-09-04 03:26
I would also find this very useful for understanding whats going on in a custom scanner during debugging. Does the lexer already keep track of it somehow for `--stat` mode possibly?

As a workaround I was thinking of using an external `$._newline_` token in my extras and potentially counting them. Ill let yall know if it works.

**Comment by amaanq** [comment] 2024-09-09 05:29
Closing as not planned (see https://github.com/tree-sitter/tree-sitter/pull/2670#issuecomment-1791455992)

**Closed by amaanq** 2024-09-09 05:29 UTC
