### ISSUE TITLE
External scanner in test

### ISSUE THREAD

**Issue by alemuller** [tree-sitter/tree-sitter#1627] opened 2022-01-29 20:20 UTC
Running `tree-sitter test` seems to combine all tests into one.

The external scanner should reset its state between test cases (or at least test files).

**Comment by ahelwer** [comment] 2022-01-29 21:00
It should be up to the external scanner to manage serializing and deserializing its own state. I've caught a bug with my external scanner because of weird behavior in `tree-sitter test`, caused by me not resetting one of my scanner state variables.

**Comment by alemuller** [comment] 2022-01-31 00:23
I expected the `tree_sitter_make_external_scanner_{create,destroy}`  to be called after every test.

The serialization seems to be working. The issue, is doesn't reset its state before running a new test.

Do I need to reset it manually?

**Comment by ahelwer** [comment] 2022-01-31 00:35
Calling `deserialize` should completely overwrite your parser's state with whatever is in the serialized data. It's good practice to clear all your state variables at the top of the `deserialize` method.

**Comment by alemuller** [comment] 2022-01-31 00:38
The serialization isn't intended to keep the state between multiples calls on the same file?

I'll read the doc.

I you want to reproduce my issue, clone [tree-sitter-make](https://github.com/alemuller/tree-sitter-make/tree/master) (master branch, not main).

Run the test:
```
$ tree-sitter test -f 1627
```

Result:
```
  ISSUE_1627:
    ✓ TS #1627 default recipe prefix (before)
    ✓ TS #1627 custom recipe prefix
    ✗ TS #1627 default recipe prefix (after)

1 failure:

expected / actual

  1. TS #1627 default recipe prefix (after):

    (makefile
      (ordinary_rule
        (targets
          (filename))
        (recipe_context
          (ERROR
            (UNEXPECTED 'c')))))
          (recipeprefix)
          (recipe
            (shell_code)))))

```

**Comment by ahelwer** [comment] 2022-01-31 00:57
The parse position can jump around arbitrarily throughout the file, so state should be fully serialized and deserialized.

**Comment by amaanq** [comment] 2024-02-17 02:01
Yeah I can see why this might've tripped you up @alemuller but @ahelwer is right, and to elaborate `create` is created when you *set* the parser, and destroy is called when you *set* another parser or destroy the parser. This way, we avoid needless allocations that a scanner might need for its state when parsing different files, and you really should consider every call to serialize/deserialize, especially ones to deserialize where the length is 0 (aka a reset). I don't think adding something to the docs would make this clear since it's expected a scanner will handle all deserialize calls, so I'll close this for now.

**Closed by amaanq** 2024-02-17 02:01 UTC
