### ISSUE TITLE
Question about files that contain multiple languages

### ISSUE THREAD

**Issue by exalted** [tree-sitter/tree-sitter#121] opened 2017-12-30 17:16 UTC
Hey there!

I am late to the party, however I like what you’re doing here @maxbrunsfeld 👏 .

A question that crossed my mind is how tree-sitter could be useful for files that contain multiple languages. A typical example could be a `foo.html` file that contain HTML, Javascript and CSS; or a `bar.js` file that contain Javascript mixed with JSX.

I am really liking the idea of incremental parsing, and I also realize maybe “language detection” isn’t a concern here; but I wonder how would, for instance, GitHub handle syntax highlighting using tree-sitter and detect to “switch“ to a different grammer for various parts of a file.

Any comments?

Thank you. 🙏

**Comment by maxbrunsfeld** [comment] 2017-12-31 05:42
Hi @exalted, great question!

JSX within JavaScript files is already supported directly by [tree-sitter-javascript](https://github.com/tree-sitter/tree-sitter-javascript). For things like JavaScript inside of HTML files and code snippets inside of Markdown files, we'll need to add a whole new feature to the system in which parsers can reference one another. It's something that I've always wanted to do. It'll probably be a fair bit of work, but it's definitely doable with the current framework. We probably won't get to for a few months though.

**Comment by exalted** [comment] 2017-12-31 06:35
> JSX within JavaScript files is already supported directly by tree-sitter-javascript.

So, ideally, JSX should be its own grammar and tree-sitter-javascript reference to it; am I right?

> For things like JavaScript inside of HTML files and code snippets inside of Markdown files, we'll need to add a whole new feature to the system in which parsers can reference one another.

That begs some questions in my mind (this is equally true also for `tree-sitter-javascript` by the way):

* A hypothetical `tree-sitter-html` grammar would delegate portions of a text to be processed by `tree-sitter-javascript` and (yet hypothetical again) `tree-sitter-css`?

* How would `tree-sitter-html` “decide” when to delegate processing to a referenced parser? (I feel like “language detection” is a whole another subject. Any opinions?)

> It's something that I've always wanted to do. It'll probably be a fair bit of work, but it's definitely doable with the current framework. We probably won't get to for a few months though.

I realize this is not a top priority (nor it should be). In case I wanted to get my hands dirty with this, with a fair amount of babysitting, where should I start to get up and running contributing to tree-sitter? 🙏

**Comment by maxbrunsfeld** [comment] 2018-01-02 03:31
> So, ideally, JSX should be its own grammar and tree-sitter-javascript reference to it; am I right?

No, I think JSX is best modeled as it already is in `tree-sitter-javascript` (and the other existing implementations like the Babel and Typescript parsers). It's not a separate language; it's just one new type of 'literal' that is added to the JavaScript language.

> A hypothetical tree-sitter-html grammar would delegate portions of a text to be processed by tree-sitter-javascript and (yet hypothetical again) tree-sitter-css?

Yeah, exactly. I'm thinking that the HTML grammar would have sections that look something like this:

```js
script_element: $ => seq(
  $.script_open_tag,
  subLanguage('javascript'),
  $.script_close_tag
),
```

where `subLanguage` is a new primitive in Tree-sitter's grammar API.

> How would tree-sitter-html “decide” when to delegate processing to a referenced parser? (I feel like “language detection” is a whole another subject. Any opinions?)

In the cases I'm thinking of and am interested in handling (JavaScript inside of HTML, CSS inside of HTML, code blocks inside of Markdown) it's very clearly defined when and how to switch languages; no *detection* is required. For example, the content of a `script` element is JavaScript, the content of a `style` element is CSS, anything inside of a `cpp`-tagged code block in Markdown is C++, etc.

Can you give an example of a case that would require some kind of detection? Generally I think of language *detection* as a problem that should be solved outside of the Tree-sitter library.

**Comment by exalted** [comment] 2018-01-02 14:37
> No, I think JSX is best modeled as it already is in tree-sitter-javascript (and the other existing implementations like the Babel and Typescript parsers). It's not a separate language; it's just one new type of 'literal' that is added to the JavaScript language.

Hm… Don’t you think both `tree-sitter-javascript` and `tree-sitter-typescript` having implemented JSX is duplication?

I feel like JSX should be parsed by `tree-sitter-jsx` as a sublanguage very much like `tree-sitter-javascript` would be a sublanguage for  `tree-sitter-markdown` in `` ```javascript `` blocks… 🤔 (No strong opinions here, however. I just hate it when diff-views are broken on github.com, especially in React components' `render` functions that return JSX; and I am hoping this sublanguage feature would solve it.)

> Can you give an example of a case that would require some kind of detection? Generally I think of language detection as a problem that should be solved outside of the Tree-sitter library.

I think you’re right. I too think _language detection_ is a separate concern and should be solved outside. And I really can’t think of a specific case that language detection would be required, assuming the text editor that uses the Tree-sitter library fires up the correct grammar based on file extensions or whatever…

**Comment by maxbrunsfeld** [comment] 2018-01-02 16:56
Luckily there isn’t duplication; tree-sitter-typescript is implemented as an extension of tree-sitter-javascript.

When I mentioned TypeScript above, I meant Microsoft’s TypeScript compiler, which, like Babel, parses JSX as an integrated part of the language (as opposed to using some kind of separate preprocessor).

**Comment by exalted** [comment] 2018-01-03 08:40
> Luckily there isn’t duplication; tree-sitter-typescript is implemented as an extension of tree-sitter-javascript.
>
> When I mentioned TypeScript above, I meant Microsoft’s TypeScript compiler, which, like Babel, parses JSX as an integrated part of the language (as opposed to using some kind of separate preprocessor).

Oh, taking a second look, I see: https://github.com/tree-sitter/tree-sitter-typescript/blob/428e09a1c4d651d9e1a3eed13d853ff84331675b/grammar.js#L23:

```js
module.exports = grammar(require('tree-sitter-javascript/grammar'), {
```

At first I saw https://github.com/tree-sitter/tree-sitter-typescript/blob/428e09a1c4d651d9e1a3eed13d853ff84331675b/grammar.js#L54 …

```js
[$.jsx_opening_element, $._primary_type, $.type_parameter],
```

… and I thought JSX was re-implemented in tree-sitter-typescript as well as in tree-sitter-javascript. I guess I should be first learning tree-sitter, before making any further observations about the state of the art.

Fair enough. ✌️ 

Thanks @maxbrunsfeld !

**Comment by pr-yemibedu** [comment] 2018-03-02 15:13
Hello,
 Language *detection* should not be possible in an easy way. It should be clear that multi language syntax is possible, but they would have clear cut points. Even if you are using Vue or Angular or Assembler in C or PHP and think you are mixing, they all really have clear points to instruct a parsing switch.

Most of the possible ways to have something that would desire *detection* is on the edge as in [Polyglot Programming](https://en.wikipedia.org/wiki/Polyglot_%28computing%29) and would not be worth the time is any early stage of development. 

The common place most people would like to see a sub language detection is when they put it in a **string** of the native language like with Regular Expressions. Thank you. Good day.

**Comment by maxbrunsfeld** [comment] 2018-03-02 18:52
> Even if you are using Vue or Angular or Assembler in C or PHP and think you are mixing, they all really have clear points to instruct a parsing switch.

:+1:

I'm going to close this out since I think we have clarity on it.

**Closed by maxbrunsfeld** 2018-03-02 18:52 UTC

**Comment by maxbrunsfeld** [comment] 2018-09-13 00:57
There's now documentation about how this language handles multi-language documents: http://tree-sitter.github.io/tree-sitter/using-parsers#multi-language-documents.

**Comment by milahu** [comment] 2020-12-02 18:50
whats the status of the 'subLanguage' feature?
or, how can i parse something like

```html
<html>
<script>
// </script>
/* </script> */
var s = '</script>';
</script>
</html>
```
.. without teaching my html-parser to recognize javascript comments or strings?
.. and without double work, since i want to parse both html and javascript?

github's dumb syntax parser shows the problem ; )
this should be colored like

<tt><<span color=green>html</span>></tt>
<tt><<span color=green>script</span>></tt>
<tt><span color=orange>// </script></span></tt>
<tt><span color=orange>/* </script> */</span></tt>
<tt><span color=red>var</span> <span color=blue>s</span> = <span color=yellow>'</script>'</span>;</tt>
<tt></<span color=green>script</span>></tt>
<tt></<span color=green>html</span>></tt>

> In case I wanted to get my hands dirty with this, with a fair amount of babysitting, where should I start to get up and running contributing to tree-sitter?

same ; )
any hints appreciated

the term 'sublanguage' is used here https://tree-sitter.github.io/tree-sitter/creating-parsers

> After developing the _type_ sublanguage a bit further, you might decide to switch to working on _statements_ or _expressions_ instead.

'sublanguage' sounds like a part / subset of the same langauge, not so much like an embedded other language

other possible names for such an API function: parse, recurse, embed, extend, switchLanguage, language, delegate, letparse

the called function also must be aware of the end-of-file-token, `</script>` in my example, so the flow-of-control returns to the caller, who can continue to parse - or: parse to the next syntax error and then return?

bonus points: parse nested xml dialects like: html > embed svg > embed html > embed svg > ....

**Comment by maxbrunsfeld** [comment] 2020-12-02 18:53
> github's dumb syntax parser shows the problem 

I think GitHub is highlighting that correctly. The script tag ends at the first `</script>` tag (it doesn't matter that it appears on the same line as a JavaScript comment.

**Comment by milahu** [comment] 2020-12-02 19:13
correct! that was unexpected

chromium and firefox parse all the `</script>` as end tags, both in JS comments and JS strings .. which makes html-parsing a bit simpler

```html
<html><script>
// say it
console.log("sorry github parser, you were right");
</script></html>
```

still .. there should be a way to avoid double-parsing and manual recursion

**Comment by maxbrunsfeld** [comment] 2020-12-02 19:22
Yeah, I don't think there is any double parsing right now. GitHub is using Tree-sitter's language injection feature to highlight that code snippet ☝️ . You can even have multiple layers of nesting, like this:

```php
<?php
function doSomePHP() {
  echo "Hello world!";
}
?>

<div id="html-within-php">
  <script>
  if (foo.bar) {
    baz.innerHTML = html `<div id="html-within-a-js-string">${moreJS()}</div>`;
  }
  </script>
</div>

<?php
doSomePHP();
?>
```

**Comment by milahu** [comment] 2020-12-02 20:05
still not happy ; )

https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection

> @injection.content - indicates that the captured node should have its contents **re-parsed** using another language.
> @injection.language - indicates that the captured node’s text may contain the name of a language that should be used to **re-parse** the @injection.content.

^ there. the content is re-parsed in a different language
after the parent language is done scanning / parsing

i still want (to help implement) that 'depth first' parsing
but is it so much more trouble than its worth?

the child parser would use dynamic delimiters and escapes
as specified by the parent parser on runtime (example: heredocs)
and/or somehow compose parsers at compile time

**Comment by maxbrunsfeld** [comment] 2020-12-02 20:11
> ^ there. the content is re-parsed in a different language, after the parent language is done scanning / parsing

Yup, I think this is the behavior that is needed for processing these kinds of nested languages correctly. We don't want the child language (JavaScript) to have any influence over when the nested document ends; that is controlled by the parent language HTML. We need that information *before* calling into the JavaScript parser.

**Comment by milahu** [comment] 2020-12-02 20:19
> We don't want the child language (JavaScript) to have any influence over when the nested document ends; that is controlled by the parent language HTML.

inversion of control .. why not? (asking the naive questions)
why yes? performance. avoid double scanning.

could this also be a technical limitation of the parser algorithm?

> we must support extensibility of grammar rules, to enable language extensions without worrying about the parser. A parser which relies on a precomputed parsing table does not easily allow such extensibility. A depth-first search based parser, however, allows adding new grammar rules on-demand when a language extension is activated (as long as their is a way of dealing with ambiguity).

http://mbeddr.com/files/gc-sle.pdf
Efficient Development of Consistent Projectional Editors using Grammar Cells

edit:

> This paper introduces new parsing and context-aware scanning algorithms in which the scanner uses contextual information to disambiguate lexical syntax. The parser uses a slightly modified LR style algorithm that passes to the scanner the set of valid symbols that the scanner may return at that point in parsing. This set is those terminals whose entries in the parse table for the current parse state are shift, reduce, or accept, but not error. The scanner then only returns tokens in this set.
>
>This scanning algorithm subordinates the disambiguation principle of maximal munch to the principle of disambiguation by context; it will return a short valid match before a long invalid match. 

https://www-users.cs.umn.edu/~evw/pubs/vanwyk07gpce/vanwyk07gpce.pdf
Context-Aware Scanning for Parsing Extensible Languages

**Comment by milahu** [comment] 2020-12-03 10:33
problem:
where should the guest parser stop parsing?
where is end-of-file in the guest language?
ideally without the guest-parser knowing the exact end-condition
which is only known at runtime
(dynamic hierarchy of end-tags with increasing precedence,
for example: `</script>`, `</foreignObject>`, `</svg>`)

possible solution:
return on syntax error on the root level,
and let the host parser decide
if the guest's syntax-error is the embed-close-tag.
if yes, the guest-parse was a success,
and the host-parser can continue to parse.
if no, the guest-parse failed -> handle syntax error

this strategy would parse html as shown in "this should be colored like"
cos `</script>` has no (magic) effect in comments or strings

sample code:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 160">
  <rect x="10" y="10" width="140" height="140" fill="none" stroke="gray" />
  <foreignObject x="20" y="20" width="120" height="120">
    <div id="_svg_html" xmlns="http://www.w3.org/1999/xhtml">
      <div>/svg/html</div>
      <style type="text/css">foreignObject>div>div { text-transform: uppercase }</style>
      <script type="text/javascript">
        // document == svg document
        var e = (...a) => document.createElementNS("http://www.w3.org/1999/xhtml", ...a);
        var ul = e("ul");
        var li = e("li"); li.innerHTML = "hello"; ul.appendChild(li);
        var li = e("li"); li.innerHTML = "world"; ul.appendChild(li);
        document.getElementById("_svg_html").appendChild(ul);
      </script>
      <!-- /svg/html/base64/gif -->
      <img width="24" style="image-rendering: pixelated; display: block; margin: auto"
        src="data:image/gif;base64,R0lGODdhBwAEAIABAAAAAP///ywAAAAABwAEAAACCExwposMD0EBADs=" />
    </div>
  </foreignObject>
</svg>
```

assume the position `</script>`
this is invalid javascript
so the javascript parser returns control
to the html parser
who will parse `</script>` as a valid tag
(the one tag he was expecting,
since handing control to the JS parser)

`</foreignObject>` is an invalid html tag
so the html parser returns to svg ..

problem:
does not work with heredocs
```
cat <<EOF
guest parser must know the token EOF
cos EOF is no syntax error in the guest language
EOF
```

**Comment by Aerijo** [comment] 2020-12-03 11:13
> inversion of control .. why not?

Because it's a massive pain when the contents aren't syntactically valid. E.g., markdown: got a code snippet like the following?
```latex
\begin{figure}[H]
```
Good luck getting control back from the LaTeX parser, it'll eat anything (by design).

Perhaps some languages are designed to hand control over to the child parser for segments like that, in which case the approach is sound. But in the majority of cases, it is the parent parser that knows when the scope ends, not the child, because the entire concept of being in some kind of sub-language scope is handled by the parent, while the child doesn't know it's only a snippet of a larger document.

Basically, you run into the problem you just mentioned 

> where should the guest parser stop parsing?

________

For your HTML example, try the following page in a browser (I did it in Firefox)
```
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <script type="text/javascript">
      console.log("hello</script>")
    </script>
  </body>
</html>
```
and then try just the script 'contents' in the dev tools
```
console.log("hello</script>")
```
The outputs are quite different. So HTML and JS disagree about where the JS scope ends; you need the HTML parser to scan anyway to determine where the end is.

**Comment by milahu** [comment] 2020-12-03 12:51
i still claim "this feature is useful in some cases" (of course not in all cases)
for example, svelte is a dialect of html that allows syntax-sugar like
```svelte
<div on:click={ (event) => { console.dir( { event } ); } }>click me</div>
```
currently i need to double-parse:
first: shallow parse to find the closing curly-brace ("teach my html-parser to count braces")
second: parse the javascript expression

**Comment by AlbertMarashi** [comment] 2024-09-05 13:47
+1 how does something like svelte handle this?

We have expressions like

```svelte
<foo bar="a string { "an expression with a string inside " } some other text">
```

**Comment by desertthunder** [comment] 2024-12-30 06:52
> There's now documentation about how this library handles multi-language documents: http://tree-sitter.github.io/tree-sitter/using-parsers#multi-language-documents.

I wanted to chime in and add an up to date link!
https://tree-sitter.github.io/tree-sitter/using-parsers/3-advanced-parsing.html?highlight=multi#multi-language-documents
