### ISSUE TITLE
`tree_sitter::QueryMatches` mutates `captures` field during iteration

### ISSUE THREAD

**Issue by Jakobeha** [tree-sitter/tree-sitter#2265] opened 2023-05-16 03:16 UTC
Related to https://github.com/tree-sitter/tree-sitter/issues/1656 and https://github.com/tree-sitter/tree-sitter/issues/608

If you `collect` a `QueryMatches`, then the earlier match's captures will be overwritten by later ones. The issue seems to be that `QueryMatches` is actually a streaming iterator, and once you call `next` the old `QueryMatches` should no longer be used.

I think this should be addressed, it violates Rust's safety guarantees since the match captures are behind an immutable reference. Also, GATs are now stable and that seemed to be a blocker.

Some possibilities:

- Make QueryMatches implement [https://docs.rs/streaming-iterator/latest/streaming_iterator/] or a similar trait, which will maintain some of the portability and convenience of being an iterator.
- Make `QueryMatches` own its captures (`Vec<QueryCapture<'tree>>`). This means we get to keep `QueryMatches` an iterator, at the cost of a slight performance hit
- Do both: create a new trait `StreamingQueryMatches` which is a streaming iterator, and make `QueryMatches` own its captures

**Comment by hadronized** [comment] 2024-02-25 15:12
[kak-tree-sitter](https://github.com/hadronized/kak-tree-sitter) author here. I have faced that exact problem lately while adding support for advanced semantics selections modification. It took me a whole day to eventually enter a discussion with @the-mikedavis (from Helix) to realize that collecting iterators is unsound with `tree-sitter`.

I’m joining @Jakobeha on this one.

**Comment by ObserverOfTime** [comment] 2024-04-13 14:08
Closing as duplicate of #608. (PR very welcome.)

**Closed by ObserverOfTime** 2024-04-13 14:08 UTC
Labels: duplicate
