### ISSUE TITLE
`generate/src/render.rs` panic: "no entry found for key"

### ISSUE THREAD

**Issue by knottio** [tree-sitter/tree-sitter#3877] opened 2024-11-03 17:30 UTC
### Problem

Consider the following simple, non-panicking grammar:
```javascript
/// <reference types="tree-sitter-cli/dsl" />
// Doesn't panic
module.exports = grammar({
  name: 'sandbox',
  extras: $ => [$.x],
  rules: {
    source_file: _ => 'a',
    x: $ => $.b,
    b: _ => 'b',
  }
})

```
Changing the `'b'` terminal to `'a'` (as follows) panics when calling `tree-sitter generate`:
```javascript
/// <reference types="tree-sitter-cli/dsl" />
// Panics
module.exports = grammar({
  name: 'sandbox',
  extras: $ => [$.x],
  rules: {
    source_file: _ => 'a',
    x: $ => $.b,
    b: _ => 'a',
  }
})
```
Or, instead, changing the name of the `b` terminal to `_b` (as follows) panics:
```javascript
/// <reference types="tree-sitter-cli/dsl" />
// Panics
module.exports = grammar({
  name: 'sandbox',
  extras: $ => [$.x],
  rules: {
    source_file: _ => 'a',
    x: $ => $._b,
    _b: _ => 'b',
  }
})
```

Note that neither of the panicking samples panic when `x` is not in extras:
```javascript
/// <reference types="tree-sitter-cli/dsl" />
// Doesn't panic
module.exports = grammar({
  name: 'sandbox',
  rules: {
    source_file: $ => $.x,
    x: $ => $.b,
    b: _ => 'a',
  }
})
```
and
```javascript
/// <reference types="tree-sitter-cli/dsl" />
// Doesn't panic
module.exports = grammar({
  name: 'sandbox',
  rules: {
    source_file: $ => $.x,
    x: $ => $._b,
    _b: _ => 'b',
  }
})
```
So it seems to have something to do specifically with `extras`.

Here's the full stack trace of the panic from version 0.23.4 (same for both samples):
```
thread 'main' panicked at cli/generate/src/render.rs:1146:36:
no entry found for key
stack backtrace:
   0:     0x558cfdf2acc0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28f16e8528a6973f
   1:     0x558cfdf6adfb - core::fmt::write::h75b6ef8f7aee1a7c
   2:     0x558cfdf43b8f - std::io::Write::write_fmt::h973b363e3c6dba24
   3:     0x558cfdf2aa7e - std::sys_common::backtrace::print::hf04e3a54197b934a
   4:     0x558cfdf1d9ea - std::panicking::default_hook::{{closure}}::hb3640bfc4d36f569
   5:     0x558cfdf1d73b - std::panicking::default_hook::h5661f6cd5eb7129d
   6:     0x558cfdf1de79 - std::panicking::rust_panic_with_hook::h3a41910ac9040dcc
   7:     0x558cfdf2b314 - std::panicking::begin_panic_handler::{{closure}}::h4a1c04c4ab6c7070
   8:     0x558cfdf2aed9 - std::sys_common::backtrace::__rust_end_short_backtrace::h21d2f857d4d898b1
   9:     0x558cfdf1db77 - rust_begin_unwind
  10:     0x558cfdab94b3 - core::panicking::panic_fmt::hbd29354903ebb815
  11:     0x558cfdab947b - core::option::expect_failed::he3c1c9fee97fd763
  12:     0x558cfdcacd5d - tree_sitter_generate::render::Generator::generate::h7bb6f7983fbd1eae
  13:     0x558cfdcb4b2e - tree_sitter_generate::render::render_c_code::h6ea699498250d9ff
  14:     0x558cfdc4ba21 - tree_sitter_generate::generate_parser_for_grammar_with_opts::hb11da2683c175402
  15:     0x558cfdc4a472 - tree_sitter_generate::generate_parser_in_directory::h70b75ddc5397388b
  16:     0x558cfdac2394 - tree_sitter::main::h08bc567143ea7309
  17:     0x558cfdb35353 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf12be8193607716e
  18:     0x558cfdb33459 - std::rt::lang_start::{{closure}}::h141989007caccd46
  19:     0x558cfdf1da67 - std::panicking::try::h313170bb1d1d6e4b
  20:     0x558cfdf2c14d - std::rt::lang_start_internal::h6cc7d681663e7b4e
  21:     0x558cfdaf6775 - main
  22:     0x7f580442a14e - __libc_start_call_main
  23:     0x7f580442a209 - __libc_start_main@@GLIBC_2.34
  24:     0x558cfdab9a45 - _start
  25:                0x0 - <unknown>
  ```
And likewise for master:
```
thread 'main' panicked at cli/generate/src/render.rs:1158:36:
no entry found for key
stack backtrace:
   0:     0x5590eeff19b7 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc7227e0e319a0b38
   1:     0x5590ef00c700 - core::fmt::write::hab7a2cb9fb1eea10
   2:     0x5590eefd314f - std::io::Write::write_fmt::h5d9ea37d99fc8ea3
   3:     0x5590eeff1784 - std::sys_common::backtrace::print::h7ef6b9088506adf3
   4:     0x5590eeff233a - std::panicking::default_hook::{{closure}}::h2be91e085f955e55
   5:     0x5590eeff2063 - std::panicking::default_hook::hd222121dd148ba89
   6:     0x5590eeff2898 - std::panicking::rust_panic_with_hook::hcb0f9a863644f6c2
   7:     0x5590eeff277a - std::panicking::begin_panic_handler::{{closure}}::hb3736c891f535df7
   8:     0x5590eeff1be6 - std::sys_common::backtrace::__rust_end_short_backtrace::h5c867a2182e2e40a
   9:     0x5590eeff24d0 - rust_begin_unwind
  10:     0x5590ef00af05 - core::panicking::panic_fmt::h71234a7826c31033
  11:     0x5590ef015513 - core::option::expect_failed::hcbf5a9b7e22cab9f
  12:     0x5590ee799ad5 - core::option::Option<T>::expect::h4542b4216d2a252f
                               at /build/rustc-1.76.0-src/library/core/src/option.rs:894:21
  13:     0x5590ee799ad5 - <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index::hbe70bf0a18199c8f
                               at /build/rustc-1.76.0-src/library/std/src/collections/hash/map.rs:1338:23
  14:     0x5590ee6ab65d - tree_sitter_generate::render::Generator::add_parse_table::h38d4bfa118b3e043
                               at /home/knottio/src/sandboxes/tree-sitter/tree-sitter/cli/generate/src/render.rs:1158:36
  15:     0x5590ee6910f7 - tree_sitter_generate::render::Generator::generate::h85f0807d0edb7369
                               at /home/knottio/src/sandboxes/tree-sitter/tree-sitter/cli/generate/src/render.rs:139:9
  16:     0x5590ee6b7903 - tree_sitter_generate::render::render_c_code::h54be17d3bc5133aa
                               at /home/knottio/src/sandboxes/tree-sitter/tree-sitter/cli/generate/src/render.rs:1722:5
  17:     0x5590ee765d14 - tree_sitter_generate::generate_parser_for_grammar_with_opts::hbfb96bb8322c39f4
                               at /home/knottio/src/sandboxes/tree-sitter/tree-sitter/cli/generate/src/lib.rs:135:18
  18:     0x5590ee764c47 - tree_sitter_generate::generate_parser_in_directory::hfe95766135f23203
                               at /home/knottio/src/sandboxes/tree-sitter/tree-sitter/cli/generate/src/lib.rs:93:9
  19:     0x5590ee35798d - tree_sitter::Generate::run::ha33f5a62eacb0edb
                               at /home/knottio/src/sandboxes/tree-sitter/tree-sitter/cli/src/main.rs:722:9
  20:     0x5590ee362e44 - tree_sitter::run::h13e8083fce90b9cd
                               at /home/knottio/src/sandboxes/tree-sitter/tree-sitter/cli/src/main.rs:1361:49
  21:     0x5590ee36196c - tree_sitter::main::hc08f4373aff1a06d
                               at /home/knottio/src/sandboxes/tree-sitter/tree-sitter/cli/src/main.rs:1306:18
  22:     0x5590ee3a12cb - core::ops::function::FnOnce::call_once::h47e28ac5c011eea7
                               at /build/rustc-1.76.0-src/library/core/src/ops/function.rs:250:5
  23:     0x5590ee3337ce - std::sys_common::backtrace::__rust_begin_short_backtrace::hb5f77bcbdb0789d0
                               at /build/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:155:18
  24:     0x5590ee34a261 - std::rt::lang_start::{{closure}}::hc502f3c6ccc542d0
                               at /build/rustc-1.76.0-src/library/std/src/rt.rs:166:18
  25:     0x5590eeff2374 - std::panicking::try::h45c8379f4866ecc7
  26:     0x5590eefea555 - std::rt::lang_start_internal::hf358ddc7f05da9a0
  27:     0x5590ee34a23a - std::rt::lang_start::he0927613a80291db
                               at /build/rustc-1.76.0-src/library/std/src/rt.rs:165:17
  28:     0x5590ee38041e - main
  29:     0x7f6f9d92510e - __libc_start_call_main
  30:     0x7f6f9d9251c9 - __libc_start_main@@GLIBC_2.34
  31:     0x5590ee32bd45 - _start
  32:                0x0 - <unknown>
  ```

### Steps to reproduce

`tree-sitter generate` the aforementioned `grammar.js` files with `0.24.3` or `0.25.0 (8588c966917a7ced61f4ec3c9e00e6e50567a1fb)`

### Expected behavior

Either a successful compile, or a descriptive error message if the grammar is invalid.

### Tree-sitter version (tree-sitter --version)

`tree-sitter 0.24.3` and `tree-sitter 0.25.0 (8588c966917a7ced61f4ec3c9e00e6e50567a1fb)` (current master)

### Operating system/version

NixOS unstable, Linux 6.6.54, x86_64

**Comment by WillLillis** [comment] 2024-11-03 20:34
Duplicate of https://github.com/tree-sitter/tree-sitter/issues/768

You are correct, the crash is due to the generator's treatment of nested nonterminal rules inside of `extras`.

**Closed by WillLillis** 2024-11-03 20:34 UTC
Labels: bug
