### ISSUE TITLE
npm i web-tree-sitter :: fail on Node 12

### ISSUE THREAD

**Issue by drom** [tree-sitter/tree-sitter#362] opened 2019-06-13 18:46 UTC
```
npm i web-tree-sitter
```
Linux, Node v12.4.0

Getting error:

```bash
../src/conversions.cc:105:41: error: no matching function for call to ‘v8::Value::NumberValue()’
  105 |   if (std::isfinite(js_row->NumberValue())) {
      |                                         ^
In file included from /home/drom/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./node.h:4,
                 from ../src/conversions.cc:1:
/home/drom/.node-gyp/12.4.0/include/node/v8.h:2564:39: note: candidate: ‘v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const’
 2564 |   V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
      |                                       ^~~~~~~~~~~
/home/drom/.node-gyp/12.4.0/include/node/v8.h:2564:39: note:   candidate expects 1 argument, 0 provided
../src/conversions.cc:106:52: error: no matching function for call to ‘v8::Value::Int32Value()’
  106 |     row = static_cast<uint32_t>(js_row->Int32Value());
      |                                                    ^
In file included from /home/drom/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./node.h:4,
                 from ../src/conversions.cc:1:
/home/drom/.node-gyp/12.4.0/include/node/v8.h:2569:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
 2569 |   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
      |                                        ^~~~~~~~~~
/home/drom/.node-gyp/12.4.0/include/node/v8.h:2569:40: note:   candidate expects 1 argument, 0 provided
../src/conversions.cc:111:44: error: no matching function for call to ‘v8::Value::NumberValue()’
  111 |   if (std::isfinite(js_column->NumberValue())) {
      |                                            ^
In file included from /home/drom/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./node.h:4,
                 from ../src/conversions.cc:1:
/home/drom/.node-gyp/12.4.0/include/node/v8.h:2564:39: note: candidate: ‘v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const’
 2564 |   V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
      |                                       ^~~~~~~~~~~
/home/drom/.node-gyp/12.4.0/include/node/v8.h:2564:39: note:   candidate expects 1 argument, 0 provided
../src/conversions.cc:112:58: error: no matching function for call to ‘v8::Value::Int32Value()’
  112 |     column = static_cast<uint32_t>(js_column->Int32Value()) * BYTES_PER_CHARACTER;
      |                                                          ^
In file included from /home/drom/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./node.h:4,
                 from ../src/conversions.cc:1:
/home/drom/.node-gyp/12.4.0/include/node/v8.h:2569:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
 2569 |   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
      |                                        ^~~~~~~~~~
/home/drom/.node-gyp/12.4.0/include/node/v8.h:2569:40: note:   candidate expects 1 argument, 0 provided
../src/conversions.cc: In function ‘Nan::Maybe<unsigned int> node_tree_sitter::ByteCountFromJS(const v8::Local<v8::Value>&)’:
../src/conversions.cc:130:47: error: no matching function for call to ‘v8::Value::Uint32Value()’
  130 |   return Nan::Just<uint32_t>(arg->Uint32Value() * BYTES_PER_CHARACTER);
      |                                               ^
In file included from /home/drom/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./node.h:4,
                 from ../src/conversions.cc:1:
/home/drom/.node-gyp/12.4.0/include/node/v8.h:2567:41: note: candidate: ‘v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const’
 2567 |   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
      |                                         ^~~~~~~~~~~
/home/drom/.node-gyp/12.4.0/include/node/v8.h:2567:41: note:   candidate expects 1 argument, 0 provided
/home/drom/.node-gyp/12.4.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/drom/.node-gyp/12.4.0/include/node/node_object_wrap.h:84:78:   required from here
/home/drom/.node-gyp/12.4.0/include/node/v8.h:9817:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
 9817 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/drom/.node-gyp/12.4.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/home/drom/.node-gyp/12.4.0/include/node/v8.h:9817:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [tree_sitter_runtime_binding.target.mk:123: Release/obj.target/tree_sitter_runtime_binding/src/conversions.o] Ошибка 1
make: выход из каталога «/home/drom/work/test1/node_modules/tree-sitter/build»
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/drom/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.1.7-1-default
gyp ERR! command "/home/drom/.nvm/versions/node/v12.4.0/bin/node" "/home/drom/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/drom/work/test1/node_modules/tree-sitter
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN test1@1.0.0 No description
npm WARN test1@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter@0.15.4 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter@0.15.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/drom/.npm/_logs/2019-06-13T18_43_34_522Z-debug.log
```

**Comment by maxbrunsfeld** [comment] 2019-06-13 18:48
This is a duplicate of https://github.com/tree-sitter/node-tree-sitter/issues/46. In general, we track the node.js-specific issues on that repo.

I started working on it in https://github.com/tree-sitter/node-tree-sitter/pull/45, but it's a bit complex, and I'm not sure when I'll have time to complete this.

**Closed by maxbrunsfeld** 2019-06-13 18:48 UTC
Labels: bug

**Comment by drom** [comment] 2019-06-14 04:39
Why do WebAssebly bindings require nan & V8 compilation?

**Comment by maxbrunsfeld** [comment] 2019-06-14 21:27
They don't. Those errors that you're seeing aren't from `web-tree-sitter`, I think `npm i` was causing `node-tree-sitter` to be recompiled, because maybe you had it in your `node_modules` folder or your package.json?
