### ISSUE TITLE
tree-sitter is blocking

### ISSUE THREAD

**Issue by juli1** [tree-sitter/tree-sitter#3199] opened 2024-03-20 18:35 UTC
### Problem

Tree-sitter is blocking when iterating on the results of a rule for Java. This is happening only with some queries.

Added a fully reproducible example for Java.

### Steps to reproduce

git clone https://github.com/juli1/tree-sitter-debug
cd tree-sitter-debug
cargo run

### Expected behavior

The program should finish.

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.22.2

### Operating system/version

macOS

**Comment by WillLillis** [comment] 2024-03-22 01:16
Tree-sitter's playground becomes unresponsive after attempting to scroll the source code box (query box is fine, syntax tree stutters a bit but also scrolls up and down) past a certain point with the same code/ query:

![ts_java_hang](https://github.com/tree-sitter/tree-sitter/assets/87077023/4ba71a76-b06e-4f30-ad88-2dc4610eb43d)

**Comment by quentinLeDilavrec** [comment] 2024-07-08 00:31
You are probably pushing tree-sitter queries further than they were designed for initially (syntax highlighting), do not hesitate to read #2038, where they discuss some limitations (especially the predicates).
In your specific case, given the current implementation of tree-sitter queries, your query is growing an exponential amount of query states proportional to the number of statements per block, even if these states are later merged.

A simple solution, to speedup the query (just above) using the c or rust api would be to simply split the query in 3, one query cursor per pattern matching a statement. And do the "(_)*" and name resolution parts in c or rust.

@ObserverOfTime maybe creating a specific tag for improper uses of queries would help with triage ?

**Comment by amaanq** [comment] 2024-08-30 03:06
Yeah, this query + file suffers from combinatorial explosion - #3559 would effectively solve this, but this is not a bug in that it blocks/hangs, so closing

**Closed by amaanq** 2024-08-30 03:06 UTC
Labels: query, perf
