### ISSUE TITLE
Docs: Creating Parser: missing a step on Project Setup

### ISSUE THREAD

**Issue by rooney** [tree-sitter/tree-sitter#3208] opened 2024-03-24 06:51 UTC
### Problem

There's a missing step in the docs for [Creating Parser](https://tree-sitter.github.io/tree-sitter/creating-parsers), Project Setup section, causing `tree-sitter generate` to fail.

### Steps to reproduce

- Follow the mentioned "Creating Parser" docs.
- When you arrive at this step: "run the following command: `tree-sitter generate`", the command will fail with the following message:
```
Failed to locate a package.json file that has a "tree-sitter" section, please ensure you have one, and if you don't then consult the docs
```

### Expected behavior

`tree-sitter generate` runs without error

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.22.2 (fc15f621334a262039ffaded5937e2844f88da61)

### Operating system/version

macOS 13.6.1

**Comment by clason** [comment] 2024-03-24 09:17
Duplicate of #3170

**Closed** 2024-03-24 09:57 UTC
Labels: bug
