### ISSUE TITLE
Tests with the `:error` attribute succeed no matter what

### ISSUE THREAD

**Issue by elliotfontaine** [tree-sitter/tree-sitter#3712] opened 2024-09-30 23:21 UTC
### Problem

When a unit test with the `:error` attribute parse the test code **without** finding any error in the tree, it will correctly displays in red in the output list of tests (meaning something not good!).

BUT `tree-sitter test` has a exit status of 0 (success) instead of 1 (fail).

### Steps to reproduce

```
==================================
simple comment 
:error
==================================
# The following S-expression is actually correct. That should raise an error!
----------------------------------
(source_file
  (comment))
```

### Expected behavior

Return code 1 for `tree-sitter parse`

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.23.0

### Operating system/version

MacOS 12.7.4

**Comment by WillLillis** [comment] 2024-10-01 02:08
Can't reproduce on latest master (see screenshot below), looks like this was fixed in bc072a52f80c46018313b3cb6dd033a585caf16f.

![image](https://github.com/user-attachments/assets/713e64b6-e0cf-48d7-8289-ef1847397d7c)

**Closed** 2024-10-01 06:52 UTC
Labels: bug
