### ISSUE TITLE
Hidden rules content unreachable for queries

### ISSUE THREAD

**Issue by jonatanklosko** [tree-sitter/tree-sitter#1441] opened 2021-10-14 17:47 UTC
## Grammar

```js
module.exports = grammar({
  name: "test",

  rules: {
    source: ($) => $.unary_operator,

    unary_operator: ($) =>
      seq(field("operator", choice("-", $._plus)), $.integer),

    _plus: ($) => "+",

    integer: ($) => /\d+/,
  },
});
```

This simple grammar is designed to parse numbers with leading + or - operator as in `+10` and `-10`.

Note that `-` is tokenized in place, while `+` is under a hidden rule.

## Unexpected behaviour

**examples/query.scm**
```
(unary_operator operator: _ @operator)
```

**examples/minus.txt**
```
-1
```

**examples/plus.txt**
```
+1
```

### Querying

Running a query specifically targeting the operator works for `-`, but not for `+`.

```
$ npx tree-sitter query examples/query.scm examples/minus.txt
examples/minus.txt
  pattern: 0
    capture: operator, start: (0, 0), text: "-"
```

```
$ npx tree-sitter query examples/query.scm examples/plus.txt
examples/plus.txt
```

### Parsing

Parsing `examples/minus.txt` works as expected, note the `-` appears in the XML output.

```
$ npx tree-sitter parse -x examples/minus.txt
(source [0, 0] - [1, 0]
  (unary_operator [0, 0] - [0, 2]
    (integer [0, 1] - [0, 2])))

<source>
  <unary_operator>-
    <integer>1</integer>
</unary_operator>
</source>
```

Parsing `examples/plus.txt` kinda works, but the `+` does not appear in the XML output.

```
$ npx tree-sitter parse -x examples/plus.txt
(source [0, 0] - [1, 0]
  (unary_operator [0, 0] - [0, 2]
    (integer [0, 1] - [0, 2])))

<source>
  <unary_operator>
    <integer>1</integer>
</unary_operator>
</source>
```

## Workaround

Creating an alias like `alias($._plus, "+")` fixes the above issues. If this is the expected solution it's fine by me, but it's not necessarily obvious and the described behaviour is confusing, so I'm reporting at least for future reference :)

**Comment by maxbrunsfeld** [comment] 2021-10-14 17:59
Yeah, this is the expected behavior because the plus node is hidden.

I guess the part that’s surprising and confusing is that, when a named rule consists of only a single token (like the plus here), we don’t create a separate node for that rule - that name is directly assigned to the token. So in this case, the plus token itself is hidden; it’s not wrapped in a hidden parent.

**Comment by amaanq** [comment] 2024-11-02 06:30
Fixed in https://github.com/tree-sitter/tree-sitter/pull/2577

**Closed by amaanq** 2024-11-02 06:29 UTC
Labels: documentation
