### ISSUE TITLE
highlight command panics with tree-sitter-cli 0.20.0

### ISSUE THREAD

**Issue by ahelwer** [tree-sitter/tree-sitter#1229] opened 2021-07-02 18:42 UTC
On Windows 10. After installing tree-sitter-cli 0.20.0, if I run `tree-sitter highlight .\Test.tla` with `RUST_BACKTRACE=full` I get the error
```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 16', cli\src\highlight.rs:359:34
stack backtrace:
   0:     0x7ff747eb190e - <unknown>
   1:     0x7ff747ece87c - <unknown>
   2:     0x7ff747ea95d8 - <unknown>
   3:     0x7ff747eb4902 - <unknown>
   4:     0x7ff747eb43e3 - <unknown>
   5:     0x7ff747eb4fa3 - <unknown>
   6:     0x7ff747eb4b51 - <unknown>
   7:     0x7ff747eb225f - <unknown>
   8:     0x7ff747eb4aa9 - <unknown>
   9:     0x7ff747f10150 - <unknown>
  10:     0x7ff747f10117 - <unknown>
  11:     0x7ff747be495e - <unknown>
  12:     0x7ff747bbdd38 - <unknown>
  13:     0x7ff747bb898f - <unknown>
  14:     0x7ff747bb60d6 - <unknown>
  15:     0x7ff747bb64ac - <unknown>
  16:     0x7ff747eb5147 - <unknown>
  17:     0x7ff747bc36a7 - <unknown>
  18:     0x7ff747eef315 - <unknown>
  19:     0x7ffc9fa67034 - BaseThreadInitThunk
  20:     0x7ffc9fba2651 - RtlUserThreadStart
----
```
The command `tree-sitter parse .\Test.tla` performs as expected.

In addition to running the above test with [tree-sitter-tlaplus](https://github.com/tlaplus-community/tree-sitter-tlaplus) I also ran it with tree-sitter-cpp with the same result. Highlight was previously working fine with tree-sitter-cli 0.19.5.

The `tree-sitter dump-languages` output is as expected:
```
scope: source.cpp
parser: "C:\\Users\\ahelwer\\source\\grammar\\tree-sitter-cpp\\"
highlights: Some(["queries/highlights.scm", "node_modules/tree-sitter-c/queries/highlights.scm"])
file_types: ["cc", "cpp", "hpp", "h"]
content_regex: None
injection_regex: None

scope: source.tlaplus
parser: "C:\\Users\\ahelwer\\source\\tlaplus\\tree-sitter-tlaplus\\"
highlights: Some(["queries/highlights.scm"])
file_types: ["tla"]
content_regex: None
injection_regex: None
```

**Comment by fwip** [comment] 2021-08-03 23:30
I am getting the same error with a grammar for awk that I am authoring:

```bash
$ npx tree-sitter-cli@0.19.5 generate && npx tree-sitter-cli@0.19.5 highlight test/examples/hello.awk
BEGIN { print "Hello, World" }
$ npx tree-sitter-cli@0.20.0 generate && npx tree-sitter-cli@0.20.0 highlight test/examples/hello.awk
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 11', cli/src/highlight.rs:359:34
stack backtrace:
   0:        0x1097f6ae4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b5b7de1c79b4b45
   1:        0x109819b9e - core::fmt::write::h65ec8c8a6aa7b549
   2:        0x1097ef5fa - std::io::Write::write_fmt::hc52e560ab9e57db4
   3:        0x1097f8b2f - std::panicking::default_hook::{{closure}}::h0974624c30a6e2b5
   4:        0x1097f8639 - std::panicking::default_hook::hda3cfa32e0773aac
   5:        0x1097f9195 - std::panicking::rust_panic_with_hook::h1cdaa4b48d8ea4a1
   6:        0x1097f8cd5 - std::panicking::begin_panic_handler::{{closure}}::h51157b4dbc4c5d91
   7:        0x1097f6f78 - std::sys_common::backtrace::__rust_end_short_backtrace::h8f7fee8b4c5a0c05
   8:        0x1097f8c3a - _rust_begin_unwind
   9:        0x10984bddf - core::panicking::panic_fmt::h28a37220b8fae52a
  10:        0x10984bda6 - core::panicking::panic_bounds_check::h9e722aa90c3cc256
  11:        0x10953eb79 - tree_sitter_cli::highlight::ansi::h3134fb19e99a4e7e
  12:        0x1094fb7f0 - tree_sitter::run::h0d4927a1edc1a911
  13:        0x1094f6c63 - tree_sitter::main::hdb72213bc64bfedf
  14:        0x1094f3c8a - std::sys_common::backtrace::__rust_begin_short_backtrace::h63c96d682da41595
  15:        0x1094f3cac - std::rt::lang_start::{{closure}}::h13a1866a455413a5
  16:        0x1097f9501 - std::rt::lang_start_internal::h37583e1fa93097c4
  17:        0x1094fe249 - _main
```

Running generate=0.20.0 and highlight=0.19.5 appears to work correctly (produces highlighted code), and the reverse of generate=0.19.5 and highlight=0.20.0 gives a slightly different error (`index out of bounds: the len is 2 but the index is 3`).

I've uploaded my `grammar.js`, `test/examples/hello.awk`, and `queries/highlights.scm` in this gist: https://gist.github.com/fwip/562ff2ed84de28cc252a0bc457c8d152

Let me know if there's anything else I can do to help debug this issue.

**Comment by ahlinc** [comment] 2021-08-04 01:13
I've checked on my side and it seems the panicking was fixed by #1233.
@ahelwer @fwip Could you build tree-sitter from the master branch and check that this issue is reproducible?

**Comment by elianiva** [comment] 2021-08-06 02:08
I also had this issue earlier and I can confirm this has been fixed on master branch

**Comment by fwip** [comment] 2021-08-18 00:04
I had some difficulty figuring out how to compile and use the tree-sitter cli from source, but I believe that I've managed it and confirmed that it fixes the panic when highlighting my grammar.

**Comment by ahlinc** [comment] 2021-09-11 19:43
I'm closing this cause all related issues were resolved and I can't reproduce this segfault.
<details><summary><i>Screenshot:</i></summary>

![Screenshot from 2021-09-11 22-40-47](https://user-images.githubusercontent.com/14666676/132959602-b0aa0566-489b-44bf-a61d-568b10a336fa.png)

</details>

@ahelwer Feel free to reopen this issue if it's still reproducible for you with `tree-sitter-cli` built from the master.

**Closed by ahlinc** 2021-09-11 19:43 UTC
Labels: bug
