### ISSUE TITLE
Should adding `tree-sitter-language` to `Cargo.toml` also move `tree-sitter` to `[dev-dependencies]`?

### ISSUE THREAD

**Issue by DavisVaughan** [tree-sitter/tree-sitter#3593] opened 2024-09-06 17:41 UTC
### Problem

This bit updates your `Cargo.toml` to use the new `tree-sitter-language`
https://github.com/tree-sitter/tree-sitter/blob/9b398c2b84f0e62bf6c7d6833848e7808faf9d3c/cli/src/generate/grammar_files.rs#L325-L341

But to run the Rust test that is auto generated, you still need `tree-sitter` as a dev-dependency. But `generate` seems to remove it entirely

<img width="397" alt="Screenshot 2024-09-06 at 1 38 55 PM" src="https://github.com/user-attachments/assets/7f166ed7-5843-410a-a024-95dc9d022d83">

### Steps to reproduce

Run `tree-sitter generate` on a grammar that doesn't use `tree-sitter-language` yet

### Expected behavior

Move `tree-sitter` to `[dev-dependencies]` so tests can still be run

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.23

### Operating system/version

macOS

**Comment by amaanq** [comment] 2024-09-06 18:34
Duplicate of #3591

**Closed by amaanq** 2024-09-06 18:34 UTC
Labels: bug
