### ISSUE TITLE
`tree-sitter test` Freezes While Testing Syntax Highlighting

### ISSUE THREAD

**Issue by LebJe** [tree-sitter/tree-sitter#1347] opened 2021-08-19 15:00 UTC
Hi,

I'm currently working on [adding syntax highlighting](https://github.com/merico-dev/tree-sitter-swift/pull/3) to an _active_ [fork](https://github.com/merico-dev/tree-sitter-swift) of [tree-sitter-swift](https://github.com/tree-sitter/tree-sitter-swift).

The parsing tests complete successfully, but when `tree-sitter test` gets to the [syntax highlighting tests](https://github.com/LebJe/tree-sitter-swift/blob/76a0ffaae60a46429c3b307456c04ce729fd9d2b/test/highlight/test.swift), it freezes.

I'm able to reproduce the issue on macOS Monterey (AArch64) and Ubuntu Linux 20.04 (x86_64), with `tree-sitter` [v0.20.0](https://github.com/tree-sitter/tree-sitter/releases/tag/v0.20.0) and with the [latest commit](https://github.com/tree-sitter/tree-sitter/commit/82d4da553e74ea2ced7eae915f8fa0ae75978d27) on the master branch.

Jeff

**Comment by ahlinc** [comment] 2021-08-19 17:32
Thank you for reporting the issue, I assume this may be related to #1318

**Comment by maxbrunsfeld** [comment] 2021-08-29 18:23
I checked out https://github.com/LebJe/tree-sitter-swift/commit/c1854ed0b251a627e62af1da1bb49a386b558359, but I can't reproduce the hang when using the latest master commit of Tree-sitter (not much has changed since the commit that you linked). I'm on macOS 10.15.7.

@ahlinc Are you able to reproduce this?

**Comment by LebJe** [comment] 2021-08-29 19:20
@maxbrunsfeld can you try adding `// <- keyword` to the [second line of test/highlight/test.swift](https://github.com/LebJe/tree-sitter-swift/blob/c1854ed0b251a627e62af1da1bb49a386b558359/test/highlight/test.swift#L2)? I had removed that line so `tree-sitter` wouldn't hang.

**Comment by maxbrunsfeld** [comment] 2021-08-29 21:47
Yes, now I can reproduce the problem. Thanks!

**Comment by maxbrunsfeld** [comment] 2021-08-29 22:04
Ok, this was due to a bug in our test-handler, which parses out all of the special `// <-` and `// ^` comments in the source file. Fixed on master.

**Closed** 2021-08-29 22:04 UTC
Labels: bug
