### ISSUE TITLE
'tree-sitter generate src/grammar.json' creates a dummy 'grammar.js'

### ISSUE THREAD

**Issue by mjambon** [tree-sitter/tree-sitter#3415] opened 2024-06-12 22:34 UTC
### Problem

We work with the JSON representation of the grammar. `src/grammar.json` is our input for generating parsers. The following command works but leaves behind a dummy `grammar.js` in the current folder:
```
$ tree-sitter generate src/grammar.json
$ cat grammar.js
/// <reference types="tree-sitter-cli/dsl" />
// @ts-check

module.exports = grammar({
  name: "generate",

  rules: {
    // TODO: add the actual grammar rules
    source_file: $ => "hello"
  }
});
```

The issue is that it creates confusion in our setup. The dummy `grammar.js` looks like it should be the grammar we're working with but it isn't.

### Steps to reproduce

# Steps to create a valid src/grammar.json
mkdir empty
cd empty
tree-sitter generate

# Steps to show that grammar.js is created even if a valid JSON grammar is provided
rm -f grammar.js
tree-sitter generate src/grammar.json

# The dummy grammar.js is back:
cat grammar.js

### Expected behavior

Don't create a dummy `grammar.js` file if a grammar is found by `tree-sitter generate` (in this case, a JSON file passed on the command line).

### Tree-sitter version (tree-sitter --version)

0.22.6

### Operating system/version

Ubuntu Linux

**Comment by ObserverOfTime** [comment] 2024-06-13 09:31
Closing as duplicate of #3300. You can gitignore the file for the time being.

**Closed by ObserverOfTime** 2024-06-13 09:31 UTC
Labels: bug

**Comment by mjambon** [comment] 2024-06-13 21:37
> You can gitignore the file for the time being.

It would be nice if people read gitignore files.
