### ISSUE TITLE
tree-sitter compatibility version

### ISSUE THREAD

**Issue by JulioJu** [tree-sitter/tree-sitter#243] opened 2018-11-28 14:35 UTC
Hi,

`tree-sitter` seems to not be compatible with all versions of node or npm. See https://github.com/tree-sitter/tree-sitter/issues/205 or https://github.com/mads-hartmann/bash-language-server/issues/93#issuecomment-442455951.

If this issue is confirmed with this versions of node of npm, maybe you could add in the `package.json` `{ "engines" : { "node" : ">=11.3.0", "npm":">=??" } }  (or other relevant version) and type command `npm config set engine-strict true` (see https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-packages-json).

Thanks in advance ! ;-)

**Comment by maxbrunsfeld** [comment] 2018-11-28 18:34
Tree-sitter works fine with node 8; I don't think that incompatibility is the reason for either of those problems.

**Comment by maxbrunsfeld** [comment] 2018-11-28 18:49
I'm going to close this out because I think it's a duplicate of https://github.com/tree-sitter/tree-sitter/issues/205.

**Closed by maxbrunsfeld** 2018-11-28 18:49 UTC
