### ISSUE TITLE
Query to capture nested quantified node

### ISSUE THREAD

**Issue by sangwoo-joh** [tree-sitter/tree-sitter#2704] opened 2023-10-12 05:30 UTC
I'm trying to capture C's function name.

For example,

```c
void foo();
```

I can use the following query for capturing `foo`:

```scheme
(declaration
 declarator: (function_declarator
  declarator: (identifier) @function-name))
```

However, if the function returns a pointer type, it gets complicated:

```c
void* foo();
```

In a single pointer, I can capture with the following query:

```scheme
(declaration
 declarator: (pointer_declarator
   declarator: (function_declarator
    declarator: (identifier) @function-name)))
```

However, C can have infinite pointers in theory, so the `(pointer_declarator :declarator ( .... ` part could become countless. For a double pointer, it becomes `(pointer_declarator :declarator (pointer_declarator :declarator (function_declarator declarator: (identifier) @function-name)))`, ans so on.

How can I capture this kind of nested quantified node in tree-sitter query syntax?

**Comment by sangwoo-joh** [comment] 2023-10-12 05:49
I've tried the following, but it didn't even be parsed :sob: 

```scheme
(declaration
 declarator: (
   (pointer_declarator declarator:)* (function_declarator
    declarator: (identifier) @function-name)))
```

**Comment by sangwoo-joh** [comment] 2023-10-12 08:21
I found that this issue could be duplicate with #880 ?

**Comment by ahlinc** [comment] 2023-10-13 10:45
> I've tried the following, but it didn't even be parsed 😭

You're not alone, my opinion is that the problem is in an approach that was chosen far times ago for the C grammar implementation and it needs to be changed with keeping in the mind of querying ergonomics and possibilities.

**Comment by ObserverOfTime** [comment] 2024-04-12 17:44
Closing as a duplicate of #880.

**Closed by ObserverOfTime** 2024-04-12 17:44 UTC
