### ISSUE TITLE
web-tree-sitter failing while other bindings are working

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/tree-sitter#1099] opened 2021-05-08 10:38 UTC
Hey,

running our test suite with the new tree sitter shows some errors. I'm still investigating, so this is just a headsup for now.

https://github.com/elm-tooling/elm-language-server/pull/590

**Comment by Razzeee** [comment] 2021-05-08 10:58
I guess it would be easier to track down, if we could get a 0.19.2 release

**Comment by jmbockhorst** [comment] 2021-05-12 13:37
I did a git bisect, and it looks like https://github.com/tree-sitter/tree-sitter/commit/a40045a419e5b0a7818c4dbc0a2ff49c8dbca822 is the commit that broke our tests.

**Comment by Razzeee** [comment] 2021-05-21 00:20
Still happening with web-tree-sitter 0.19.4, without rebuilding the parser.

**Comment by maxbrunsfeld** [comment] 2021-05-21 00:29
So, in that commit that @jmbockhorst mentioned, there were two intentional changes:
* `get_column()` previously returned a character count, and now it returns a byte count
* Previously, if you edited a tree such that a token's column changed, and that token was produced by an external scanner that called `get_column()`, the token *still* might be (incorrectly) reused on the next parse. Now, that token is marked as "changed", so it will have to be re-scanned on the next parse.

I'm not sure what kind of breakage you're seeing. Could it be caused by one of these intentional changes? If not, maybe that commit introduced a bug, but I'm not sure what it would be yet. Could you try to describe the expected behavior vs the actual behavior that you're seeing?

**Comment by Razzeee** [comment] 2021-05-21 00:39
That the weird thing, I would expect those `get_column()` changes to already fail tests in the https://github.com/elm-tooling/tree-sitter-elm repo and not fail on usage with the new web tree sitter bindings.
It's weird, that we can just exchange the binding and end up with problems all of a sudden, without updating the wasm.

**Comment by jmbockhorst** [comment] 2021-05-21 00:43
I'm thinking it has to do with the `get_column()` change, because its failing around tab spacing parsing and our custom scanner. But I'm not sure why it broke without the binding being changed.

**Comment by Razzeee** [comment] 2021-05-23 16:03
Not sure if you really mean the `tab` key being parsed, as we do have some example code with tab/instead of space. But changing these to space still causes this problem.

**Comment by jmbockhorst** [comment] 2021-05-23 16:05
Yeah, I'm just saying it seems like all failures are related to case expressions. I was debugging one of the tests, and it was parsing the `case_of_branch` with and `ERROR` node.

**Comment by Razzeee** [comment] 2021-05-23 17:24
I did some testing of 0.19.5 vs 0.19.1.

This is one example of a failing test according to the test suite
```
================================================================================
Test regression
================================================================================
f x =
    case x of
        0 -> 0
        y -> 2 * y
      --X      --^
--------------------------------------------------------------------------------

(file
  (value_declaration
    (function_declaration_left
      (lower_case_identifier)
      (lower_pattern
        (lower_case_identifier)))
    (eq)
    (case_of_expr
      (case)
      (value_expr
        (value_qid
          (lower_case_identifier)))
      (of)
      (case_of_branch
        (pattern
          (number_constant_expr
            (number_literal)))
        (arrow)
        (number_constant_expr
          (number_literal)))
      (case_of_branch
        (pattern
          (lower_pattern
            (lower_case_identifier)))
        (arrow)
        (bin_op_expr
          (number_constant_expr
            (number_literal))
          (operator
            (operator_identifier))
          (value_expr
            (value_qid
              (lower_case_identifier)))))
      (line_comment))))

```

Doesn't show a regression.

I've then created used the same code to run this on both version

`npx tree-sitter parse ./examples/test.elm > logfail.log`

`npx tree-sitter parse ./examples/test.elm > logok.log`

And diffed them without, they matched.

I then added this to our scanner.cc where we use `get_column`

```
auto column = lexer->get_column(lexer);
printf("Column: %i\n", column);
indent_length_stack.push_back(column);
```

And redid the parsing from before, both seemed to return 8 and thus matched.

**Comment by Razzeee** [comment] 2021-05-24 22:22
Reverting to this part
https://github.com/tree-sitter/tree-sitter/commit/a40045a419e5b0a7818c4dbc0a2ff49c8dbca822#diff-f0e22a4bc6491c2183969edc9cd63232a28e6bde1a9bdb730df0970302d3240cL236-L254

and still including https://github.com/tree-sitter/tree-sitter/commit/a40045a419e5b0a7818c4dbc0a2ff49c8dbca822#diff-f0e22a4bc6491c2183969edc9cd63232a28e6bde1a9bdb730df0970302d3240cR236 seems to fix our test suite.

**Comment by Razzeee** [comment] 2021-05-24 23:10
I now tried calling `advance` according to the times `get_column` returns when using it, but that doesn't seem to help either. In our part of the parser.

**Comment by Razzeee** [comment] 2021-05-25 23:39
If I use https://github.com/Razzeee/tree-sitter/commit/db2f52b87245e4bf639361720021c3ee8afb9046 (which works fine) and replace `return result;` with `return self->current_position.extent.column;` it will fail again. Removing the other statements in that diff seem to cause the same problem.

**Comment by Razzeee** [comment] 2021-05-26 20:23
I think this is as far as I can go. @maxbrunsfeld can you advice?

**Comment by maxbrunsfeld** [comment] 2021-05-26 20:35
It seems like changing the return value of `get_colum` to be in units of *bytes* instead of characters has affected of the logic in your external scanner? Did you debug what your scanner is doing to determine why it matters? If you're calling this through `web-tree-sitter`, there will generally be two bytes per character (because JavaScript strings are UTF16, and `web-tree-sitter` encodes them this way).

I would think that you'd just need to debug what's going on in your scanner when you parse that failing example. Is it relying on specific numbers being returned from `get_column`?

**Comment by maxbrunsfeld** [comment] 2021-05-26 20:49
> If I use Razzeee@db2f52b (which works fine) and replace `return result;` with `return self->current_position.extent.column;` it will fail again.

> Removing the other statements in that diff seem to cause the same problem.

Actually, I don't understand this part of what you said. You said that the failure happens when you replace `return result` with `return self->current_position.extent.column`. But then you also said that removing other statements in the diff causes the problem? Can you clarify - What is the smallest change that causes the problem?

Specifically, if you revert back to the last commit of Tree-sitter where your tests *pass*, and then you just change the body of `ts_lexer__get_column` to return bytes instead of characters:

```c
static uint32_t ts_lexer__get_column(TSLexer *payload) {
  Lexer *self = (Lexer *)payload;
  return self->current_position.extent.column;
}
```

Do your tests then fail? If so, then I think you just need to debug your external scanner and figure out why it matters whether the column is in units of bytes vs characters.

**Comment by Razzeee** [comment] 2021-05-27 00:01
> It seems like changing the return value of `get_colum` to be in units of _bytes_ instead of characters has affected of the logic in your external scanner? Did you debug what your scanner is doing to determine why it matters? If you're calling this through `web-tree-sitter`, there will generally be two bytes per character (because JavaScript strings are UTF16, and `web-tree-sitter` encodes them this way).
> 
> I would think that you'd just need to debug what's going on in your scanner when you parse that failing example. Is it relying on specific numbers being returned from `get_column`?

It's kind of relying on those numbers, but should be fine, if they are consistent to each other. Printing the numbers didn't show anything obvious, but I didn't test it via `web-tree-sitter` in that case, as I'm not sure how to do that and still get the scanner logs.

I kind of think it only happens, when we're using the parser via web-tree-sitter. I think we can also use the old version of web-tree-sitter, with a newer build of the parser and it still works. (should double check this)

> > If I use [Razzeee/tree-sitter@db2f52b](https://github.com/Razzeee/tree-sitter/commit/db2f52b) (which works fine) and replace `return result;` with `return self->current_position.extent.column;` it will fail again.
> 
> > Removing the other statements in that diff seem to cause the same problem.
> 
> Actually, I don't understand this part of what you said. You said that the failure happens when you replace `return result` with `return self->current_position.extent.column`. But then you also said that removing other statements in the diff causes the problem? Can you clarify - What is the smallest change that causes the problem?

There are multiple ways to cause it, coming from the linked diff: 
1. change `return self->current_position.extent.column`
2. remove the `ts_lexer__get_lookahead` call
3. removing other `ts_lexer` calls. I didn't check all, but seemed to be true for most. Might be in parts due to it changing `result`

> 
> Specifically, if you revert back to the last commit of Tree-sitter where your tests _pass_, and then you just change the body of `ts_lexer__get_column` to return bytes instead of characters:
> 
> ```c
> static uint32_t ts_lexer__get_column(TSLexer *payload) {
>   Lexer *self = (Lexer *)payload;
>   return self->current_position.extent.column;
> }
> ```
> 
> Do your tests then fail? If so, then I think you just need to debug your external scanner and figure out why it matters whether the column is in units of bytes vs characters.

Yes, they also fail with that code.

**Comment by maxbrunsfeld** [comment] 2021-05-27 01:58
Ok, thanks. So switching to returning bytes is an intentional change. Can you try and figure out why it is a problem for the elm external scanner?

**Comment by Razzeee** [comment] 2021-05-27 23:24
I still think it's web tree sitter somehow. It doesn't seem to match what tree-sitter itself is doing.

If I just parse 
```
module Test exposing (..)

func a =
    case a of
        1 ->
            ""

        2 -> 
            ""
```
in the elm-tree-sitter test suite it parses fine.

![image](https://user-images.githubusercontent.com/5943908/119908291-8dabc480-bf52-11eb-950e-9a673fc70b3a.png)


If I parse it in the language server repo via web-tree-sitter and debug into the tree I can see error nodes.

![image](https://user-images.githubusercontent.com/5943908/119908488-fdba4a80-bf52-11eb-824d-22892d916387.png)
This is the `>` in the second to the last line. While it still might be our scanner, I'm not understanding how that could be possible - as running the tests doesn't show this behavior.

**Comment by Razzeee** [comment] 2021-05-30 03:21
I think I've found it.

https://github.com/elm-tooling/tree-sitter-elm/pull/98

> If you're calling this through web-tree-sitter, there will generally be two bytes per character (because JavaScript strings are UTF16, and web-tree-sitter encodes them this way).

Was a great tip, I guess this is at the root. Still, I wish the test suite would be able to catch this somehow.

Also big thanks to @ahlinc for posting about the logging here https://github.com/tree-sitter/tree-sitter/issues/1129#issuecomment-849872835

**Closed** 2021-05-30 12:27 UTC
