### ISSUE TITLE
Collecting QueryCaptures is different from iterating through it directly

### ISSUE THREAD

**Issue by ubolonton** [tree-sitter/tree-sitter#608] opened 2020-04-28 14:23 UTC
I used this code to iterate through captures:

```rust
let capture_names = query.capture_names();
let captures = cursor.captures(query, node, text_callback).collect::<Vec<_>>();
for (m, capture_index) in captures {
    let c = m.captures[capture_index];
    println!("{}\t{:#?}\t{}", 
             m.pattern_index, c.node.byte_range(), 
             capture_names[c.index as usize]);
}
```

With the [highlights query](https://github.com/tree-sitter/tree-sitter-rust/blob/3e5ec5a/queries/highlights.scm) from the latest version of tree-sitter-rust (3e5ec5a), and this piece of Rust code:
```rust
// a
unsafe {
    b.c()
}
```

The result is incorrect:

```
16      22..23  punctuation.bracket
57      22..23  punctuation.bracket
25      22..23  punctuation.bracket
5       20..21  function.method
15      22..23  punctuation.bracket
18      22..23  punctuation.bracket
19      22..23  punctuation.bracket
```

If I iterate through `QueryCaptures` directly (removing the `collect()` call), then the result is correct:

```
16      0..4    comment
57      5..11   keyword
25      19..20  punctuation.delimiter
5       20..21  function.method
15      20..21  property
18      21..22  punctuation.bracket
19      22..23  punctuation.bracket
```

**Comment by maxbrunsfeld** [comment] 2020-04-28 19:51
Oh, this is a bug in the lifetimes on the `.captures` method. You shouldn't be allowed to `collect` on that iterator, because the iterator's `Item` should contain a shared reference to the `QueryCursor`. This was fixed for the `.matches` method in https://github.com/tree-sitter/tree-sitter/issues/530.

**Comment by maxbrunsfeld** [comment] 2020-04-28 20:07
One option is to change the return type of `QueryCursor::captures` to the abstract type `impl Iterator<Item = (QueryMatch<'a>, usize)>` - this seems to solve the problem for `QueryCursor::matches`.

The problem is that this iterator is stored in a struct in https://github.com/tree-sitter/tree-sitter/blob/c393591e1db759c0f16f877165a6370d06b22472/highlight/src/lib.rs#L102. If we turn it into an abstract type, then a bunch of structs need to be made unnecessarily generic. Maybe this is ok though.

**Comment by ubolonton** [comment] 2020-04-29 12:28
Changing `QueryCursor::captures` to return `Iterator<Item = (QueryMatch<'a>, usize)>` wouldn't prevent the use of `collect`. I tried it.

I think the desired invariant sounds like *`Item` can only be consumed before moving on to the next iteration*, i.e. something like this:

```rust
    fn next(&'iter mut self) -> Option<(QueryMatch<'iter>, usize)>
```

Which is currently [not possible with Iterator](https://users.rust-lang.org/t/implement-iterator-for-item-with-lifetimes/21842), without [GATs](https://lukaskalbertodt.github.io/2018/08/03/solving-the-generalized-streaming-iterator-problem-without-gats.html).

There are 3 options I can think of:
- Mark `QueryCursor::captures` as unsafe, explaining how the iterator should be used.
- Use [StreamingIterator](https://docs.rs/streaming-iterator/0.1.5/streaming_iterator/) as the alternative iteration mechanism.
- Use a callback as the alternative iteration mechanism.

**Comment by maxbrunsfeld** [comment] 2020-04-29 16:43
Yeah, you are right, this is a streaming iterator pattern, and we'd really want GATs. I think for now, we should switch to returning `impl Iterator` from `captures`.

**Comment by pmd3d** [comment] 2024-06-11 01:53
I'm interested in using the GATs feature of Rust to try to fix this issue,
It looks like the GATs issue is closed, and it is part of the language now: https://github.com/rust-lang/rust/issues/44265
I will need a lot of time though as I'm not very experienced with Rust yet.
But this issue is marked "good-first-issue" so I assume that is ok.
Could you please assign me?
But, if I give up, I will comment on this thread to unassign me.

**Comment by pmd3d** [comment] 2024-07-06 05:04
I need to pass on working on this. I've signed up for a training class for about a year. I will check back here to see what happens when the class ends.

**Comment by umanwizard** [comment] 2024-09-28 22:26
Hi all (cc @ObserverOfTime )

Is there any update on this? Is there any blocker for #3504 that we can help resolve?

This is quite a serious source of UB in the tree-sitter Rust bindings, so hopefully it can be resolved sometime soon.

**Comment by amaanq** [comment] 2024-09-29 21:37
Fixed in https://github.com/tree-sitter/tree-sitter/pull/3504

**Closed by amaanq** 2024-09-29 21:37 UTC
Labels: bug, good-first-issue, rust
