### ISSUE TITLE
[Question] Can't parse valid code

### ISSUE THREAD

**Issue by bglgwyng** [tree-sitter/tree-sitter#519] opened 2020-01-07 15:00 UTC
I created a repo for this question.
https://github.com/bglgwyng/tree-sitter-sandbox

You can consider the example grammar as a very subset of Haskell only including `arrow`, `apply` and `parenthesis`.
There are three examples and all of them are valid code.

Try
```shell
tree-sitter parse example-file-1
tree-sitter parse example-file-2
tree-sitter parse example-file-3
```
then you can see only `example-file-3` is failed for parsing, because of trailing whitespace right before the closing parenthesis.
> I set `extras` to empty, so I had to consume whitespace manually.
```
(a -> b c ) // after 'c'
```
And I can't see the reason while the others are parsed successfully.

**Comment by maxbrunsfeld** [comment] 2020-01-07 22:16
I believe the problem is that the `whitespace` nodes are introducing some additional ambiguity into the grammar, and the `prec.left`/`prec.right` calls are unintentionally resolving this ambiguity to *always* prefer one interpretation of the whitespace.

In general, I would not recommend including `whitespace` in specific places within each rule like this. You really want to handle whitespace in the scanner, not the grammar itself, otherwise it will add an un-manageable amount of ambiguity to your syntax.

**Closed by maxbrunsfeld** 2020-01-07 22:16 UTC
Labels: question

**Comment by bglgwyng** [comment] 2020-01-08 05:00
@maxbrunsfeld  Can I see the generated parsing table?

**Comment by maxbrunsfeld** [comment] 2020-01-17 00:34
The generated parser table is written to `src/parser.c`. There's some indirection in the way that it's represented but you can use it to follow along during parsing. Run `tree-sitter parser file -D` to generate a graphviz graph of the parsing process.
