### ISSUE TITLE
Possibly UB

### ISSUE THREAD

**Issue by zajac** [tree-sitter/tree-sitter#420] opened 2019-08-11 18:25 UTC
We experience segfaults with incremental parsing using Tree Sitter.
Trying to isolate the problem we found this program to hang on a certain iteration.
I do get that we kind of abuse the API here by supplying a wrong Edit. 
What is really suspicious is that it doesn't immediately stuck when certain i is supplied, it spends some number of iterations. 
It feels like parser has some hidden state that is corrupted or the tree passed is corrupted.
This is the best test case we could get, trying to debug out initial problem with the segfault (btw we don't feed tree-sitter with wrong edits, so our initial problem could be something different).

```
  FILE *f = fopen("/Users/jetzajac/Projects/jsitter/testData/router_go", "r");
  fseek (f, 0, SEEK_END);
  size_t s = ftell(f);
  rewind(f);
  void *b = malloc(s);
  fread(b, s, 1, f);
  TSParser *parser = ts_parser_new();
  ts_parser_set_language(parser, tree_sitter_go());
  TSTree *tree = ts_parser_parse_string(parser,
                                        NULL,
                                        (const char *)b,
                                        s);

  for (int i = 0; i < 100; ++i) {
    printf("i = %d\n", i);
    //str_insert(1000 + i, 'x', b, s + i);
    TSTree *copy = ts_tree_copy(tree);
    TSInputEdit e; // + 8
    e.start_byte = 2000;
    e.old_end_byte = 2000;
    e.new_end_byte = 2000 + i;
    ts_tree_edit(copy, &e);
    TSTree *new_tree = ts_parser_parse_string(parser, copy, b, s);
    ts_tree_delete(copy);
    ts_tree_delete(new_tree);
    ts_parser_reset(parser);
  }
```

the file router_go can be found here:
https://github.com/JetBrains/jsitter/blob/master/testData/router_go

**Comment by maxbrunsfeld** [comment] 2019-08-12 17:17
> What is really suspicious is that it doesn't immediately stuck when certain `i` is supplied, it spends some number of iterations.

What do you mean by this, exactly?

For me, there doesn't seem to be any stateful behavior. The program reliably hangs when `i == 2`. It doesn't hang infinitely; the parse actually does complete eventually, but it's very very slow, probably because the reused tree is out-of-sync with the source code in an unexpected way.

> btw we don't feed tree-sitter with wrong edits, so our initial problem could be something different

Yeah, I think it's probably something different, because this is just a slow parse, not a segfault.

**Comment by zajac** [comment] 2019-08-12 18:11
I don't see it hangs on i = 2, I see it hangs only when i = 0 and i = 1 was supplied before that. 
I've tried to replace for with just i = 2 and it worked fine. This is what I found to be suspicious.

**Comment by zajac** [comment] 2019-08-12 18:17
Ok I see, there was a mistake in my observation when I was writing it. It does hang now when loop is initialized with i = 2. What I seemed to see is that it hangs only when i = 0 and i = 1 steps were performed earlier. But this is a mistake. Sorry.

**Comment by zajac** [comment] 2019-08-12 18:19
What we have now is an example when TS segfaults, but we fail to isolate it to a simple C program. It might be something else involved.

**Comment by maxbrunsfeld** [comment] 2019-08-12 18:28
I'm going to close this out for right now, but feel free to reopen it if you find a different reproduction case that causes a segfault. I'd definitely want to find out what's causing the problem and fix it.

**Closed by maxbrunsfeld** 2019-08-12 18:28 UTC
