### ISSUE TITLE
Tree-sitter-CLI on cargo is old and fails to install with latest rust nightly

### ISSUE THREAD

**Issue by xylix** [tree-sitter/tree-sitter#820] opened 2020-11-28 09:09 UTC
Latest tree-sitter-cli on Cargo is 0.14.5 from february 2019. Could it be updated?

On my machine, `RUST_BACKTRACE=1 cargo install tree-sitter-cli` fails with
```
error: failed to run custom build command for `tree-sitter-cli v0.14.5`
```
using cargo `cargo 1.50.0-nightly (bfca1cd22 2020-11-24)` and rustc `rustc 1.50.0-nightly (6a889570e 2020-11-27)`

```
Caused by:
  process didn't exit successfully: `/var/folders/yh/01qfv1252618td_z27c2ch2h0000gp/T/cargo-installK005Fd/release/build/tree-sitter-cli-8c10de5419f075d1/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'assertion failed: repo_path.pop()', /Users/xylix/.cargo/registry/src/github.com-1ecc6299db9ec823/tree-sitter-cli-0.14.5/build.rs:22:13
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/6a889570e46c03d7b156ec08f3f4cb4d145924a3/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/6a889570e46c03d7b156ec08f3f4cb4d145924a3/library/core/src/panicking.rs:92:14
     2: core::panicking::panic
               at /rustc/6a889570e46c03d7b156ec08f3f4cb4d145924a3/library/core/src/panicking.rs:50:5
     3: build_script_build::read_git_sha
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `tree-sitter-cli v0.14.5`, intermediate artifacts can be found at `/var/folders/yh/01qfv1252618td_z27c2ch2h0000gp/T/cargo-installK005Fd`

Caused by:
  build failed
```

Unlike this `cargo install`, cloning the repo and building from source works just fine with latest nightly rust.

**Comment by samestep** [comment] 2021-02-04 02:22
Same issue here (also this is a duplicate of #610 and #352 I think). I'm currently getting around it like this:
```sh
cargo install --rev 0.18.0 --git https://github.com/tree-sitter/tree-sitter.git tree-sitter-cli
```

**Comment by ahlinc** [comment] 2023-01-06 05:39
`tree-sitter-cli v0.20.7` is on [crates.io](https://crates.io/crates/tree-sitter-cli)

**Closed by ahlinc** 2023-01-06 05:39 UTC
