### ISSUE TITLE
Tree-sitter and semantic highlighting

### ISSUE THREAD

**Issue by p-e-w** [tree-sitter/tree-sitter#65] opened 2017-03-05 05:41 UTC
As far as I understand, tree-sitter currently produces an AST that for highlighting purposes will be recursively collapsed into scope lists which in an editor like Atom will then become class lists to which styling can be applied. In other words, the resulting markup as a basis for highlighting is conceptually identical to that generated by TextMate grammars, while the processing is hopefully more accurate, detailed (more fine-grained scope differentiation), and performant.

Unfortunately, a flattened scope tree is missing information required for [semantic highlighting](https://medium.com/programming-ideas-tutorial-and-experience/coding-in-color-3a6db2743a1e), a form of highlighting that differentiates identifiers of the same type, such as two variables declared in succession. The problem is that tokens of the same type at the same level in the scope hierarchy are assigned the same class and thus cannot be highlighted differently.

I have [tried in the past](https://github.com/p-e-w/language-javascript-semantic) to work around this problem by intercepting the output of an external parser and generating ad-hoc scopes based on the token text. This was always a hack, and I have since given up work on that package because it relies on a private Atom API that has repeatedly changed in the past and broken the package as a result.

But now tree-sitter is coming, and this could be a golden opportunity to enable semantic highlighting for just about any language.

---

The idea is as follows: From a program like

```javascript
var one = 1
var two = 2
```

tree-sitter currently generates an AST resembling

```
program
  var_declaration
    identifier
    number
  var_declaration
    identifier
    number
```

The editor translates the AST into token annotations which result in something like

```html
<div class="program">
  <div class="var_declaration">
    var <div class="identifier">one</div> = <div class="number">1</div>
  </div>
  <div class="var_declaration">
    var <div class="identifier">two</div> = <div class="number">2</div>
  </div>
</div>
```

(I'm aware that's not how Atom's DOM actually looks, but the concept is the same).

We're now stuck, because both `one` and `two` have the same DOM path `.program .var_declaration .identifier` and thus any stylesheet will highlight them the same, which is the opposite of what we want in semantic highlighting.

The change needed for semantic highlighting happiness is that the component taking source + AST and producing annotated tokens (which I guess is [tree-sitter-syntax](https://github.com/atom/tree-sitter-syntax)) maintains, at each level of the scope hierarchy, an indexed list of identifier names and appends `index-[INDEX]` to the class list, turning the above into

```html
<div class="program">
  <div class="var_declaration">
    var <div class="identifier index-1">one</div> = <div class="number">1</div>
  </div>
  <div class="var_declaration">
    var <div class="identifier index-2">two</div> = <div class="number">2</div>
  </div>
</div>
```

Each identifier can now be assigned a color that is unique within the scope in which the identifier is valid. There are of course corner cases such as imported identifiers or languages having a `global` construct of sorts that allows breaking out of a syntax scope but in the overwhelming majority of cases this should provide accurate semantic highlighting in the sense that "same color in same scope = semantically identical identifier". The idea could be extended further by indexing *scopes* as well, effectively recreating some of the original parsing information in the class hierarchy.

---

I wasn't quite sure which repo to post this to. There might not be any changes needed to tree-sitter itself but I don't know the project well enough to know this for sure. Please feel free to move this issue somewhere else if you feel it is more appropriate there.

**Comment by maxbrunsfeld** [comment] 2017-03-06 21:06
@p-e-w This is a really cool idea. I think it will take some exploring to figure out how to implement it efficiently.

Tree-sitter already has the fairly complicated responsibility of updating the parse tree correctly after edits in an acceptable amount of time, so I don't think I want to make the core library responsible for maintaining a symbol table and an awareness of languages' scoping semantics. But I would think that you could probably do this work in a separate library *using* tree-sitter's output. 

Like you said, `tree-sitter-syntax` is the package that integrates tree-sitter into Atom's syntax highlighting system. If you're interested in experimenting with this, you may want to take a look at the [TreeSitterDecorationLayer](https://github.com/atom/tree-sitter-syntax/blob/master/lib/tree-sitter-decoration-layer.js) to get an idea of how we use the tree to create scopes. Maybe you'd just want to fork `tree-sitter-syntax` for now, while you experiment.

Ultimately, I'd like for the code `tree-sitter-syntax` to move into Atom core, but it lives in that package for now, while we're still developing the functionality.

**Comment by p-e-w** [comment] 2017-03-19 16:16
@maxbrunsfeld: I'm unable to set up `tree-sitter-syntax` on my system due to https://github.com/tree-sitter/node-tree-sitter/issues/4.

**Comment by pr-yemibedu** [comment] 2018-03-02 21:24
Hello,
 The tracking of index-XXXX throughout would be tough. You would need to possibly keep the whole chain for some trees. Modelling a view of code would not be limited to a developer having good practices (like DRY).

 Probably you would need:
 ``` html
 <div class="identifier module-1 function-1 index-1">one</div> 
 <div class="identifier module-2 function-1 index-1">one</div> 
 <div class="identifier module-2 function-2 index-1">one</div> 
```
 to allow a user ID without clashing with the programming standard library, a 3rd-party inclusion, and there own definition to support uniqueness. This is just to point out that you will quickly hit some places in common source repositories where you will not be able to style only an individual unit without the extra tracking.

 Some semantics do not need that much detail. For example, all looping may be allowed to color the same or all global values may color different than any local. So that may truly be a better library utility where you do a descent that will inject **parse paths** to support those instances. Thank you. Good day.

**Comment by maxbrunsfeld** [comment] 2018-03-03 01:12
@p-e-w I'm going to close this out since this isn't an issue with Tree-sitter itself, but more of a feature request for Atom.

> Honestly I believe semantic highlighting belongs in core, not in a separate package.

I don't think this is going to happen in the near future, because the "team" working on Tree-sitter in Atom core is one person (me) and if this functionality moves into core, it becomes my responsibility to maintain.

> The code required is language-agnostic and minimal in size

It's true the code is very nice and small. The problem is just that if it moves into core, then every minor feature request regarding this feature ("can we better distinguish keywords", "can we tweak the color palette", "can object properties *not* have this treatment", "can type names *not* have this treatment"), has to be triaged and handled by me.

> More importantly, semantic highlighting needs support from the syntax theme

I don't think that's necessarily the case. Even if the feature is in core, it's unlikely that every syntax theme author is going to define a ton of new colors. And [the way you implemented it](https://github.com/atom-archive/tree-sitter-syntax/pull/1) in `tree-sitter-syntax` didn't require changing the syntax themes. You could even reference the syntax theme the way that [the one UI themes do](https://github.com/atom/one-light-ui/blob/master/styles/ui-variables-custom.less) in order to define colors that make sense with any theme.

**Closed by maxbrunsfeld** 2018-03-03 01:12 UTC
