### ISSUE TITLE
How the ast is created? Why is the imediate node not generated?

### ISSUE THREAD

**Issue by yang-guangliang** [tree-sitter/tree-sitter#2571] opened 2023-08-26 13:33 UTC
Hi, recently, I am using tree-sitter to traverse AST. But I am so confused that why sometimes imediate nodes were not shown up.

For example, in this rule 
```
comment: $ => choice(
      $.line_comment,
      $.block_comment,
    ),
```

The node (node.type=comment) is not created. There is only the node, whose type is either line_comment or block_comment.

In another two rules
```
expression_statement: $ => seq(
      $.expression,
      ';'
    ),
expression: $ => choice(
      $.assignment_expression,
      $.binary_expression,
      ....
    ),
```
In an expression_statement node, its children only have the subtypes of "expression" (e.g. binary_expression), rather than the "expression" type itself. There are no nodes whose types are expression.

In these case, the imediate nodes with the types "comment" and "expression" are directly ignored. They are not generated in practice. So what's the princples of AST parsing and generating? When will a type be used and generated? When will it not be?

Regards,
Yang

**Comment by ahlinc** [comment] 2023-08-26 23:59
Could you provide reproducible examples on a real grammar?

_I think for the first case what you called immediate node are extra nodes in terms of Tree-sitter._

**Comment by yang-guangliang** [comment] 2023-08-27 00:44
Hi Ahlinc, I only have this example:
```
System.out.println(
            name + " is the best platform to learn "
            + field);
```
Its nested AST is reflected in the output of node.sexp():
```
(expression_statement 
   (method_invocation 
        object: 
           (field_access 
                object: (identifier) 
                field: (identifier)) 
         name: ...
         arguments: ...             
```
Based on the related rules, 
```
expression_statement: $ => seq(
      $.expression,
      ';'
    ),
expression: $ => choice(
      ....
      $.primary_expression,
      ...
primary_expression: $ => choice(
      ...
      $.method_invocation,
```
the expression_statement node should include:
```
expression_statement -> expression -> primary_expression -> method_invocation
```
But as shown in sexp(), in practice, it is 
```
expression_statement -> method_invocation
```

It seems in the process of the construction of AST, tree-sitter tries its best to compact and simplify the structure by removing the verbose node without essential information, like expression.

This optimization work is actually awesome. But some difficulty arises when converting AST to IR. I would like to understand, in regular, when this node simplification process will occur.

There are several crucial methods for parsing rules:
```
seq(rule1, rule2, ...) 
choice(rule1, rule2, ...)
repeat(rule)
repeat1(rule)
optional(rule)
prec(number, rule)
field(name, rule)
....
```
In these above methods, is only choice()  optimized and simpified?

for example,
```
a: $ => seq(
           $.b
)
b: $ => choice(
           $.c,
           $.d
```
A strcutre "a-b-c" will be optimized to "a-c".

Does this only happen for choice()? What about other cases? Is it possible to disable the optimizations? Do you know how others deal with these?

**Comment by ahlinc** [comment] 2023-08-27 14:23
It would be awesome to see a link on a real grammar if it's publicly available.

---

> the expression_statement node should include:
> ```
> expression_statement -> expression -> primary_expression -> method_invocation
> ```
> But as shown in sexp(), in practice, it is 
> ```
> expression_statement -> method_invocation
> ```

It looks like in the grammar the `expression` and `primary_expression` rules actually have a prefix underscore in their names what means [hidden rules](https://tree-sitter.github.io/tree-sitter/creating-parsers#hiding-rules).

**Comment by ahlinc** [comment] 2023-08-27 14:41
> In these above methods, is only choice() optimized and simpified?

Currently Tree-sitter don't do any optimizations it behaves pretty straightforward, it will do some optimizations for rules that have no sense like `foo: => seq("bar"),` with producing a warning that wrapping `seq` over string literal token has no sense.

For your task you need to understand how two things work:
* [Hiding rules](https://tree-sitter.github.io/tree-sitter/creating-parsers#hiding-rules) - just hides a rule node _(flattens its content)_ in a resulting tree but technically such rule will exist.
* [Inlining rules](https://tree-sitter.github.io/tree-sitter/creating-parsers#the-grammar-dsl) _(look for an `inline` word)_ - when a rule really would be eliminated and in all places references on it would be substituted by its content.

> Is it possible to disable the optimizations?

For now making rules non hidden is only possible by making changes in `grammar.js` or in `grammar.json` by stripping prefix underscores and regenerating the grammar.

> Do you know how others deal with these?

By making changes in grammars definitions.

In the future there will be an API for this things.

**Comment by ahlinc** [comment] 2023-08-28 11:29
I'm closing this question issue because all possible replies were provided, feel free to continue conversation in this issue if it would be needed.

**Closed by ahlinc** 2023-08-28 11:29 UTC

**Comment by yang-guangliang** [comment] 2023-08-28 13:53
Sure. Thank you so much!

**Comment by yang-guangliang** [comment] 2023-09-10 13:36
Hi @ahlinc, thanks for your help again. Now I can clearly parse Java's code. But there is another difficulty when reading C++ grammar.js. C++'s grammar.js is totally different from Java's.

In C++'s [grammar.js](https://github.com/tree-sitter/tree-sitter-cpp/blob/master/grammar.js#L200C14-L200C14) 
```
function_definition: ($, original) => ({
      ...original,
      members: original.members.map(
        (e) => e.name !== 'body' ?
          e :
          field('body', choice(e.content, $.try_statement))),
    }),
```

'$' seems an ast node, but what does 'original' mean here? Inside the rule, the "original" content seems unwrapped. Unlike Java, this is a little bit hard to understand.

Thanks,
Yang

**Comment by yang-guangliang** [comment] 2023-09-10 14:23
Is this because the CPP grammar is inheited from C grammar. So "original" means C's rule? During AST parsing, C++ needs to conduct instrumentation?

**Comment by ahlinc** [comment] 2023-09-10 16:07
@yang-guangliang yes, there is an extending mechanism in Tree-sitter and it used in several grammars like C/C++ or JS/Typescript, unfortunately it doesn't described in documentation yet. As you've correctly assumed the `original` is **a rule's content** for a rule with the same name but defined in a base grammar. The base grammar can be defined as a first parameter for the `grammar(base, { rules: ... })` function. The `$` identifier is used for **referencing** rules in the current or the base grammars, but when you need to substitute a content from _a base rule with the same name_ you need to use the `original` parameter.
All Tree-sitter's DSL functions are a sort of syntactic sugar on top of pure JSON, and as JS objects are easily serializable into JSON maps then every TS DSL function produces a simple JS object that would be easily serialized into a JSON map. So defining a grammar on Tree-sitter's DSL as a result is a combining predefined JSON maps by using simple JS functions that are fabrics for such JSON maps.

For every rule that you can't find in C++ grammar you need to looking for it in the base C grammar.

**Comment by yang-guangliang** [comment] 2023-09-10 17:12
Awesome! The grammar design has been proven powerful, intelligent and effecitive! 

Thanks a lot for the detailed explanation. Perhaps you might consider adding such clear explanations to the official website.
